import { normalizeLocale } from "@/utils/locale";

const SOURCE_LABEL_OVERRIDES = {
  weibo: { en: "Weibo Hot Search" },
  zhihu: { en: "Zhihu Hot List" },
  douyin: { en: "Douyin Hot List" },
  bilibili: { en: "Bilibili Trending" },
  toutiao: { en: "Toutiao Hot List" },
  baidu: { en: "Baidu Hot Search" },
  kuaishou: { en: "Kuaishou Trending" },
  "36kr": { en: "36Kr Trending" },
  "qq-news": { en: "Tencent News Trending" },
  "netease-news": { en: "Netease News Trending" },
  "sina-news": { en: "Sina News Trending" },
  ithome: { en: "ITHome Trending" },
  sspai: { en: "SSPAI Trending" },
  thepaper: { en: "The Paper Trending" },
  tieba: { en: "Baidu Tieba Trending" },
  smzdm: { en: "SMZDM Trending" },
  nytimes: { en: "The New York Times" },
  "douban-group": { en: "Douban Groups" },
  "douban-movie": { en: "Douban Movies & TV" },
  weread: { en: "WeRead Trending" },
  csdn: { en: "CSDN Trending" },
  juejin: { en: "Juejin Trending" },
  hupu: { en: "Hupu Trending" },
  coolapk: { en: "Coolapk Trending" },
  v2ex: { en: "V2EX Trending" },
  github: { en: "GitHub Trending" },
  gameres: { en: "GameRes Trending" },
  yystv: { en: "Yystv Trending" },
  miyoushe: { en: "Miyoushe Trending" },
  genshin: { en: "Genshin Impact" },
  starrail: { en: "Honkai: Star Rail" },
  honkai: { en: "Honkai Impact 3rd" },
  lol: { en: "League of Legends" },
  huxiu: { en: "Huxiu Trending" },
  sina: { en: "Sina Hot List" },
  tianya: { en: "Tianya Curated" },
  ngabbs: { en: "NGA Trending" },
  hellogithub: { en: "HelloGitHub Trending" },
  jianshu: { en: "Jianshu Trending" },
  "zhihu-daily": { en: "Zhihu Daily" },
  "openrouter-rankings": { en: "OpenRouter" },
  artificialanalysis: { en: "Artificial Analysis" },
  lmarena: {
    "zh-CN": "Arena AI",
    "zh-TW": "Arena AI",
    en: "Arena AI",
    ja: "Arena AI",
    ko: "Arena AI",
  },
  "arena-ai": { en: "Arena AI" },
  designarena: { en: "DesignArena" },
  "aicpb-rankings": { en: "AICPB Global AI Rankings" },
  "llm-stats": { en: "LLM Stats" },
  "skills-rank": { en: "Skills Rank" },
  openai: { en: "OpenAI" },
  "openai-news": { en: "OpenAI" },
  "openai-research": { en: "OpenAI" },
  "anthropic-news": { en: "Anthropic" },
  "deepmind-blog": { en: "DeepMind" },
  "meta-ai-blog": { en: "Meta AI" },
  huggingface: { en: "Hugging Face" },
  "huggingface-blog": { en: "Hugging Face" },
  "mistral-news": { en: "Mistral" },
  "cohere-blog": { en: "Cohere" },
  "hf-models": { en: "Hugging Face" },
  "hf-papers": { en: "Hugging Face" },
  paperswithcode: { en: "Papers with Code" },
  "producthunt-ai": { en: "Product Hunt" },
  "hackernews-ai": { en: "Hacker News" },
  "clawhub-skills": { en: "ClawHub Skills" },
  clawhub: { en: "ClawHub" },
  "clawhub-plugins": { en: "ClawHub Plugins" },
  "sina-ai": { en: "Sina AI" },
};

const SOURCE_LABEL_LOCALIZATIONS = {
  douyin: {
    "zh-CN": "抖音热榜",
    "zh-TW": "抖音熱榜",
    en: "Douyin Hot List",
    ja: "Douyin急上昇",
    ko: "Douyin 인기",
  },
  baidu: {
    "zh-CN": "百度热搜",
    "zh-TW": "百度熱搜",
    en: "Baidu Hot Search",
    ja: "Baidu急上昇検索",
    ko: "Baidu 인기 검색어",
  },
  kuaishou: {
    "zh-CN": "快手热榜",
    "zh-TW": "快手熱榜",
    en: "Kuaishou Trending",
    ja: "Kuaishouトレンド",
    ko: "Kuaishou 트렌드",
  },
  weibo: {
    "zh-CN": "微博热搜",
    "zh-TW": "微博熱搜",
    en: "Weibo Hot Search",
    ja: "Weibo急上昇検索",
    ko: "Weibo 인기 검색어",
  },
  toutiao: {
    "zh-CN": "今日头条热榜",
    "zh-TW": "今日頭條熱榜",
    en: "Toutiao Hot List",
    ja: "Toutiao急上昇",
    ko: "Toutiao 인기",
  },
  "qq-news": {
    "zh-CN": "腾讯新闻热榜",
    "zh-TW": "騰訊新聞熱榜",
    en: "Tencent News Trending",
    ja: "Tencent Newsトレンド",
    ko: "Tencent News 트렌드",
  },
  "netease-news": {
    "zh-CN": "网易新闻热榜",
    "zh-TW": "網易新聞熱榜",
    en: "Netease News Trending",
    ja: "Netease Newsトレンド",
    ko: "Netease News 트렌드",
  },
  "sina-news": {
    "zh-CN": "新浪新闻热榜",
    "zh-TW": "新浪新聞熱榜",
    en: "Sina News Trending",
    ja: "Sina Newsトレンド",
    ko: "Sina News 트렌드",
  },
  bilibili: {
    "zh-CN": "哔哩哔哩热榜",
    "zh-TW": "嗶哩嗶哩熱榜",
    en: "Bilibili Trending",
    ja: "Bilibiliトレンド",
    ko: "Bilibili 트렌드",
  },
  zhihu: {
    "zh-CN": "知乎热榜",
    "zh-TW": "知乎熱榜",
    en: "Zhihu Hot List",
    ja: "Zhihu人気",
    ko: "Zhihu 인기",
  },
  tieba: {
    "zh-CN": "百度贴吧热榜",
    "zh-TW": "百度貼吧熱榜",
    en: "Baidu Tieba Trending",
    ja: "Baidu Tiebaトレンド",
    ko: "Baidu Tieba 트렌드",
  },
  smzdm: {
    "zh-CN": "什么值得买热榜",
    "zh-TW": "什麼值得買熱榜",
    en: "SMZDM Trending",
    ja: "SMZDMトレンド",
    ko: "SMZDM 트렌드",
  },
  thepaper: {
    "zh-CN": "澎湃新闻热榜",
    "zh-TW": "澎湃新聞熱榜",
    en: "The Paper Trending",
    ja: "The Paperトレンド",
    ko: "The Paper 트렌드",
  },
  sina: {
    "zh-CN": "新浪热榜",
    "zh-TW": "新浪熱榜",
    en: "Sina Hot List",
    ja: "Sina人気ランキング",
    ko: "Sina 인기 랭킹",
  },
  "douban-group": {
    "zh-CN": "豆瓣讨论小组",
    "zh-TW": "豆瓣討論小組",
    en: "Douban Groups",
    ja: "Doubanグループ",
    ko: "Douban 그룹",
  },
  "douban-movie": {
    "zh-CN": "豆瓣电影",
    "zh-TW": "豆瓣電影",
    en: "Douban Movies & TV",
    ja: "Douban映画・ドラマ",
    ko: "Douban 영화·TV",
  },
  weread: {
    "zh-CN": "微信读书热榜",
    "zh-TW": "微信讀書熱榜",
    en: "WeRead Trending",
    ja: "WeReadトレンド",
    ko: "WeRead 트렌드",
  },
  "36kr": {
    "zh-CN": "36氪热榜",
    "zh-TW": "36氪熱榜",
    en: "36Kr Trending",
    ja: "36Krトレンド",
    ko: "36Kr 트렌드",
  },
  ithome: {
    "zh-CN": "IT之家热榜",
    "zh-TW": "IT之家熱榜",
    en: "ITHome Trending",
    ja: "ITHomeトレンド",
    ko: "ITHome 트렌드",
  },
  sspai: {
    "zh-CN": "少数派热榜",
    "zh-TW": "少數派熱榜",
    en: "SSPAI Trending",
    ja: "SSPAIトレンド",
    ko: "SSPAI 트렌드",
  },
  csdn: {
    "zh-CN": "CSDN 热榜",
    "zh-TW": "CSDN 熱榜",
    en: "CSDN Trending",
    ja: "CSDNトレンド",
    ko: "CSDN 트렌드",
  },
  juejin: {
    "zh-CN": "稀土掘金热榜",
    "zh-TW": "稀土掘金熱榜",
    en: "Juejin Trending",
    ja: "Juejinトレンド",
    ko: "Juejin 트렌드",
  },
  hupu: {
    "zh-CN": "虎扑热榜",
    "zh-TW": "虎撲熱榜",
    en: "Hupu Trending",
    ja: "Hupuトレンド",
    ko: "Hupu 트렌드",
  },
  coolapk: {
    "zh-CN": "酷安热榜",
    "zh-TW": "酷安熱榜",
    en: "Coolapk Trending",
    ja: "Coolapkトレンド",
    ko: "Coolapk 트렌드",
  },
  huxiu: {
    "zh-CN": "虎嗅热榜",
    "zh-TW": "虎嗅熱榜",
    en: "Huxiu Trending",
    ja: "Huxiuトレンド",
    ko: "Huxiu 트렌드",
  },
  dgtle: {
    "zh-CN": "数字尾巴热榜",
    "zh-TW": "數字尾巴熱榜",
    en: "Dgtle Trending",
    ja: "Dgtleトレンド",
    ko: "Dgtle 트렌드",
  },
  ifanr: {
    "zh-CN": "爱范儿热榜",
    "zh-TW": "愛范兒熱榜",
    en: "ifanr Trending",
    ja: "ifanrトレンド",
    ko: "ifanr 트렌드",
  },
  geekpark: {
    "zh-CN": "极客公园热榜",
    "zh-TW": "極客公園熱榜",
    en: "GeekPark Trending",
    ja: "GeekParkトレンド",
    ko: "GeekPark 트렌드",
  },
  guokr: {
    "zh-CN": "果壳热榜",
    "zh-TW": "果殼熱榜",
    en: "Guokr Trending",
    ja: "Guokrトレンド",
    ko: "Guokr 트렌드",
  },
  "zhihu-daily": {
    "zh-CN": "知乎日报",
    "zh-TW": "知乎日報",
    en: "Zhihu Daily",
    ja: "Zhihu Daily",
    ko: "Zhihu Daily",
  },
  gameres: {
    "zh-CN": "游戏葡萄热榜",
    "zh-TW": "遊戲葡萄熱榜",
    en: "GameRes Trending",
    ja: "GameResトレンド",
    ko: "GameRes 트렌드",
  },
  yystv: {
    "zh-CN": "游研社热榜",
    "zh-TW": "遊研社熱榜",
    en: "Yystv Trending",
    ja: "Yystvトレンド",
    ko: "Yystv 트렌드",
  },
  miyoushe: {
    "zh-CN": "米游社热榜",
    "zh-TW": "米遊社熱榜",
    en: "Miyoushe Trending",
    ja: "Miyousheトレンド",
    ko: "Miyoushe 트렌드",
  },
  "52pojie": {
    "zh-CN": "吾爱破解热榜",
    "zh-TW": "吾愛破解熱榜",
    en: "52pojie Trending",
    ja: "52pojieトレンド",
    ko: "52pojie 트렌드",
  },
  hostloc: {
    "zh-CN": "全球主机交流热榜",
    "zh-TW": "全球主機交流熱榜",
    en: "Hostloc Trending",
    ja: "Hostlocトレンド",
    ko: "Hostloc 트렌드",
  },
  tianya: {
    "zh-CN": "天涯社区精选",
    "zh-TW": "天涯社群精選",
    en: "Tianya Curated",
    ja: "Tianyaセレクト",
    ko: "Tianya 큐레이션",
  },
  newsmth: {
    "zh-CN": "水木社区热榜",
    "zh-TW": "水木社群熱榜",
    en: "NewSMTH Trending",
    ja: "NewSMTHトレンド",
    ko: "NewSMTH 트렌드",
  },
  github: {
    "zh-CN": "GitHub 趋势",
    "zh-TW": "GitHub 趨勢",
    en: "GitHub Trending",
    ja: "GitHubトレンド",
    ko: "GitHub 트렌드",
  },
  linuxdo: {
    "zh-CN": "Linux.do 热榜",
    "zh-TW": "Linux.do 熱榜",
    en: "Linux.do Trending",
    ja: "Linux.doトレンド",
    ko: "Linux.do 트렌드",
  },
  nytimes: {
    "zh-CN": "纽约时报",
    "zh-TW": "紐約時報",
    en: "The New York Times",
    ja: "ニューヨーク・タイムズ",
    ko: "뉴욕타임스",
  },
  v2ex: {
    "zh-CN": "V2EX",
    "zh-TW": "V2EX",
    en: "V2EX",
    ja: "V2EX",
    ko: "V2EX",
  },
  genshin: {
    "zh-CN": "原神",
    "zh-TW": "原神",
    en: "Genshin Impact",
    ja: "原神",
    ko: "원신",
  },
  starrail: {
    "zh-CN": "崩坏：星穹铁道",
    "zh-TW": "崩壞：星穹鐵道",
    en: "Honkai: Star Rail",
    ja: "崩壊：スターレイル",
    ko: "붕괴: 스타레일",
  },
  honkai: {
    "zh-CN": "崩坏3",
    "zh-TW": "崩壞3",
    en: "Honkai Impact 3rd",
    ja: "崩壊3rd",
    ko: "붕괴3rd",
  },
  lol: {
    "zh-CN": "英雄联盟",
    "zh-TW": "英雄聯盟",
    en: "League of Legends",
    ja: "League of Legends",
    ko: "리그 오브 레전드",
  },
  acfun: {
    "zh-CN": "AcFun",
    "zh-TW": "AcFun",
    en: "AcFun",
    ja: "AcFun",
    ko: "AcFun",
  },
  ngabbs: {
    "zh-CN": "NGA",
    "zh-TW": "NGA",
    en: "NGA",
    ja: "NGA",
    ko: "NGA",
  },
  nodeseek: {
    "zh-CN": "NodeSeek",
    "zh-TW": "NodeSeek",
    en: "NodeSeek",
    ja: "NodeSeek",
    ko: "NodeSeek",
  },
  producthunt: {
    "zh-CN": "Product Hunt",
    "zh-TW": "Product Hunt",
    en: "Product Hunt",
    ja: "Product Hunt",
    ko: "Product Hunt",
  },
  hackernews: {
    "zh-CN": "Hacker News",
    "zh-TW": "Hacker News",
    en: "Hacker News",
    ja: "Hacker News",
    ko: "Hacker News",
  },
  hellogithub: {
    "zh-CN": "HelloGitHub",
    "zh-TW": "HelloGitHub",
    en: "HelloGitHub",
    ja: "HelloGitHub",
    ko: "HelloGitHub",
  },
  "51cto": {
    "zh-CN": "51CTO",
    "zh-TW": "51CTO",
    en: "51CTO",
    ja: "51CTO",
    ko: "51CTO",
  },
  "ithome-xijiayi": {
    "zh-CN": "IT之家「喜加一」",
    "zh-TW": "IT之家「喜加一」",
    en: "ITHome Free Games",
    ja: "ITHome無料配布",
    ko: "ITHome 무료 배포",
  },
  jianshu: {
    "zh-CN": "简书",
    "zh-TW": "簡書",
    en: "Jianshu",
    ja: "Jianshu",
    ko: "Jianshu",
  },
  weatheralarm: {
    "zh-CN": "中央气象台",
    "zh-TW": "中央氣象台",
    en: "National Meteorological Center",
    ja: "中国中央気象台",
    ko: "중국 중앙기상대",
  },
  history: {
    "zh-CN": "历史上的今天",
    "zh-TW": "歷史上的今天",
    en: "Today in History",
    ja: "今日は何の日",
    ko: "오늘의 역사",
  },
  earthquake: {
    "zh-CN": "中国地震台",
    "zh-TW": "中國地震台",
    en: "China Earthquake Networks Center",
    ja: "中国地震台",
    ko: "중국 지진대",
  },
  "openrouter-rankings": {
    "zh-CN": "OpenRouter",
    "zh-TW": "OpenRouter",
    en: "OpenRouter",
    ja: "OpenRouter",
    ko: "OpenRouter",
  },
  artificialanalysis: {
    "zh-CN": "Artificial Analysis",
    "zh-TW": "Artificial Analysis",
    en: "Artificial Analysis",
    ja: "Artificial Analysis",
    ko: "Artificial Analysis",
  },
  "arena-ai": {
    "zh-CN": "Arena AI",
    "zh-TW": "Arena AI",
    en: "Arena AI",
    ja: "Arena AI",
    ko: "Arena AI",
  },
  designarena: {
    "zh-CN": "DesignArena",
    "zh-TW": "DesignArena",
    en: "DesignArena",
    ja: "DesignArena",
    ko: "DesignArena",
  },
  "aicpb-rankings": {
    "zh-CN": "AICPB",
    "zh-TW": "AICPB",
    en: "AICPB",
    ja: "AICPB",
    ko: "AICPB",
  },
  "llm-stats": {
    "zh-CN": "LLM Stats",
    "zh-TW": "LLM Stats",
    en: "LLM Stats",
    ja: "LLM Stats",
    ko: "LLM Stats",
  },
  "skills-rank": {
    "zh-CN": "Skills Rank",
    "zh-TW": "Skills Rank",
    en: "Skills Rank",
    ja: "Skills Rank",
    ko: "Skills Rank",
  },
  clawhub: {
    "zh-CN": "ClawHub",
    "zh-TW": "ClawHub",
    en: "ClawHub",
    ja: "ClawHub",
    ko: "ClawHub",
  },
  openai: {
    "zh-CN": "OpenAI",
    "zh-TW": "OpenAI",
    en: "OpenAI",
    ja: "OpenAI",
    ko: "OpenAI",
  },
  "anthropic-news": {
    "zh-CN": "Anthropic",
    "zh-TW": "Anthropic",
    en: "Anthropic",
    ja: "Anthropic",
    ko: "Anthropic",
  },
  "deepmind-blog": {
    "zh-CN": "DeepMind",
    "zh-TW": "DeepMind",
    en: "DeepMind",
    ja: "DeepMind",
    ko: "DeepMind",
  },
  "meta-ai-blog": {
    "zh-CN": "Meta AI",
    "zh-TW": "Meta AI",
    en: "Meta AI",
    ja: "Meta AI",
    ko: "Meta AI",
  },
  "mistral-news": {
    "zh-CN": "Mistral",
    "zh-TW": "Mistral",
    en: "Mistral",
    ja: "Mistral",
    ko: "Mistral",
  },
  "cohere-blog": {
    "zh-CN": "Cohere",
    "zh-TW": "Cohere",
    en: "Cohere",
    ja: "Cohere",
    ko: "Cohere",
  },
  "perplexity-blog": {
    "zh-CN": "Perplexity",
    "zh-TW": "Perplexity",
    en: "Perplexity",
    ja: "Perplexity",
    ko: "Perplexity",
  },
  "xai-news": {
    "zh-CN": "xAI",
    "zh-TW": "xAI",
    en: "xAI",
    ja: "xAI",
    ko: "xAI",
  },
  huggingface: {
    "zh-CN": "Hugging Face",
    "zh-TW": "Hugging Face",
    en: "Hugging Face",
    ja: "Hugging Face",
    ko: "Hugging Face",
  },
  paperswithcode: {
    "zh-CN": "Papers with Code",
    "zh-TW": "Papers with Code",
    en: "Papers with Code",
    ja: "Papers with Code",
    ko: "Papers with Code",
  },
  "producthunt-ai": {
    "zh-CN": "Product Hunt",
    "zh-TW": "Product Hunt",
    en: "Product Hunt",
    ja: "Product Hunt",
    ko: "Product Hunt",
  },
  "hackernews-ai": {
    "zh-CN": "Hacker News",
    "zh-TW": "Hacker News",
    en: "Hacker News",
    ja: "Hacker News",
    ko: "Hacker News",
  },
  "reddit-localllama": {
    "zh-CN": "Reddit /r/LocalLLaMA",
    "zh-TW": "Reddit /r/LocalLLaMA",
    en: "Reddit /r/LocalLLaMA",
    ja: "Reddit /r/LocalLLaMA",
    ko: "Reddit /r/LocalLLaMA",
  },
  "reddit-machinelearning": {
    "zh-CN": "Reddit /r/MachineLearning",
    "zh-TW": "Reddit /r/MachineLearning",
    en: "Reddit /r/MachineLearning",
    ja: "Reddit /r/MachineLearning",
    ko: "Reddit /r/MachineLearning",
  },
  "reddit-artificial": {
    "zh-CN": "Reddit /r/artificial",
    "zh-TW": "Reddit /r/artificial",
    en: "Reddit /r/artificial",
    ja: "Reddit /r/artificial",
    ko: "Reddit /r/artificial",
  },
  "sina-ai": {
    "zh-CN": "新浪 AI 热榜",
    "zh-TW": "新浪 AI 熱榜",
    en: "Sina AI",
    ja: "Sina AIトレンド",
    ko: "Sina AI 트렌드",
  },
};

const SOURCE_DISPLAY_LABEL_OVERRIDES = {
  "clawhub-skills": {
    "zh-CN": "ClawHub",
    "zh-TW": "ClawHub",
    en: "ClawHub",
    ja: "ClawHub",
    ko: "ClawHub",
  },
  "clawhub-plugins": {
    "zh-CN": "ClawHub",
    "zh-TW": "ClawHub",
    en: "ClawHub",
    ja: "ClawHub",
    ko: "ClawHub",
  },
};

const SOURCE_DISPLAY_SUFFIXES = {
  "zh-CN": [
    "热门文章榜",
    "热榜",
    "热搜",
    "趋势",
    "热议",
    "精选",
    "排行榜",
  ],
  "zh-TW": [
    "熱門文章榜",
    "熱榜",
    "熱搜",
    "趨勢",
    "熱議",
    "精選",
    "排行榜",
  ],
  en: [
    " Hot Search",
    " Hot List",
    " Trending",
    " Rankings",
    " Ranking",
    " Curated",
  ],
  ja: [
    "急上昇検索",
    "人気ランキング",
    "急上昇",
    "トレンド",
    "人気",
    "セレクト",
  ],
  ko: [
    " 인기 검색어",
    " 인기 랭킹",
    " 트렌드",
    " 인기",
    " 큐레이션",
  ],
};

const GENERIC_SOURCE_SUBTITLE_LABELS = {
  "zh-CN": ["热榜"],
  "zh-TW": ["熱榜"],
  en: ["Hot List"],
  ja: ["人気ランキング"],
  ko: ["인기 랭킹"],
};

Object.entries(SOURCE_LABEL_LOCALIZATIONS).forEach(([sourceName, labels]) => {
  SOURCE_LABEL_OVERRIDES[sourceName] = {
    ...(SOURCE_LABEL_OVERRIDES[sourceName] || {}),
    ...labels,
  };
});

const GROUP_LABEL_OVERRIDES = {
  agentic: {
    "zh-CN": "Agentic",
    "zh-TW": "Agentic",
    en: "Agentic",
    ja: "Agentic",
    ko: "Agentic",
  },
  quality: {
    "zh-CN": "质量与使用",
    "zh-TW": "品質與使用",
    en: "Quality & Usage",
    ja: "品質と利用",
    ko: "품질·사용량",
  },
  image: {
    "zh-CN": "图像",
    "zh-TW": "圖像",
    en: "Image",
    ja: "画像",
    ko: "이미지",
  },
  video: {
    "zh-CN": "视频",
    "zh-TW": "影片",
    en: "Video",
    ja: "動画",
    ko: "비디오",
  },
  audio: {
    "zh-CN": "音频",
    "zh-TW": "音訊",
    en: "Audio",
    ja: "音声",
    ko: "오디오",
  },
  builders: {
    "zh-CN": "构建器",
    "zh-TW": "建構器",
    en: "Builders",
    ja: "ビルダー",
    ko: "빌더",
  },
  slides: {
    "zh-CN": "演示文稿",
    "zh-TW": "簡報",
    en: "Slides",
    ja: "スライド",
    ko: "슬라이드",
  },
  usage: {
    "zh-CN": "热度",
    "zh-TW": "熱度",
    en: "Usage",
    ja: "利用状況",
    ko: "사용량",
  },
  ecosystem: {
    "zh-CN": "生态",
    "zh-TW": "生態",
    en: "Ecosystem",
    ja: "エコシステム",
    ko: "생태계",
  },
  scene: {
    "zh-CN": "场景",
    "zh-TW": "場景",
    en: "Use Cases",
    ja: "ユースケース",
    ko: "활용 장면",
  },
  cinema: {
    "zh-CN": "热映",
    "zh-TW": "熱映",
    en: "Now Showing",
    ja: "上映中",
    ko: "상영 중",
  },
  new: {
    "zh-CN": "新片榜",
    "zh-TW": "新片榜",
    en: "New Releases",
    ja: "新作",
    ko: "신작",
  },
  movie: {
    "zh-CN": "电影",
    "zh-TW": "電影",
    en: "Movie",
    ja: "映画",
    ko: "영화",
  },
  tv: {
    "zh-CN": "电视剧",
    "zh-TW": "電視劇",
    en: "TV",
    ja: "ドラマ",
    ko: "드라마",
  },
  frontend: {
    "zh-CN": "前端",
    "zh-TW": "前端",
    en: "Frontend",
    ja: "フロントエンド",
    ko: "프론트엔드",
  },
  creative: {
    "zh-CN": "创意",
    "zh-TW": "創意",
    en: "Creative",
    ja: "クリエイティブ",
    ko: "크리에이티브",
  },
  media: {
    "zh-CN": "媒体",
    "zh-TW": "媒體",
    en: "Media",
    ja: "メディア",
    ko: "미디어",
  },
  chat: {
    "zh-CN": "对话",
    "zh-TW": "對話",
    en: "Chat",
    ja: "対話",
    ko: "채팅",
  },
  code: {
    "zh-CN": "代码",
    "zh-TW": "程式",
    en: "Code",
    ja: "コード",
    ko: "코드",
  },
  image: {
    "zh-CN": "图像",
    "zh-TW": "圖像",
    en: "Image",
    ja: "画像",
    ko: "이미지",
  },
  video: {
    "zh-CN": "视频",
    "zh-TW": "影片",
    en: "Video",
    ja: "動画",
    ko: "비디오",
  },
  core: {
    "zh-CN": "综合",
    "zh-TW": "綜合",
    en: "Core",
    ja: "総合",
    ko: "종합",
  },
  scenario: {
    "zh-CN": "场景",
    "zh-TW": "場景",
    en: "Scenarios",
    ja: "シナリオ",
    ko: "시나리오",
  },
  global: {
    "zh-CN": "全球",
    "zh-TW": "全球",
    en: "Global",
    ja: "グローバル",
    ko: "글로벌",
  },
  segments: {
    "zh-CN": "细分",
    "zh-TW": "細分",
    en: "Segments",
    ja: "細分",
    ko: "세분",
  },
  growth: {
    "zh-CN": "增速",
    "zh-TW": "增速",
    en: "Growth",
    ja: "成長",
    ko: "성장",
  },
  skills: {
    "zh-CN": "技能",
    "zh-TW": "技能",
    en: "Skills",
    ja: "スキル",
    ko: "스킬",
  },
  plugins: {
    "zh-CN": "插件",
    "zh-TW": "外掛",
    en: "Plugins",
    ja: "プラグイン",
    ko: "플러그인",
  },
  sort: {
    "zh-CN": "榜单",
    "zh-TW": "榜單",
    en: "Rankings",
    ja: "ランキング",
    ko: "랭킹",
  },
  rank: {
    "zh-CN": "榜单",
    "zh-TW": "榜單",
    en: "Rankings",
    ja: "ランキング",
    ko: "랭킹",
  },
  period: {
    "zh-CN": "周期",
    "zh-TW": "週期",
    en: "Period",
    ja: "期間",
    ko: "기간",
  },
  partition: {
    "zh-CN": "分区",
    "zh-TW": "分區",
    en: "Sections",
    ja: "カテゴリ",
    ko: "섹션",
  },
  board: {
    "zh-CN": "板块",
    "zh-TW": "看板",
    en: "Boards",
    ja: "掲示板",
    ko: "게시판",
  },
  topic: {
    "zh-CN": "主题",
    "zh-TW": "主題",
    en: "Topics",
    ja: "トピック",
    ko: "주제",
  },
  news: {
    "zh-CN": "动态",
    "zh-TW": "動態",
    en: "Updates",
    ja: "更新",
    ko: "소식",
  },
  feed: {
    "zh-CN": "资讯",
    "zh-TW": "資訊",
    en: "News",
    ja: "ニュース",
    ko: "뉴스",
  },
  channel: {
    "zh-CN": "频道",
    "zh-TW": "頻道",
    en: "Channels",
    ja: "チャンネル",
    ko: "채널",
  },
  category: {
    "zh-CN": "分类",
    "zh-TW": "分類",
    en: "Categories",
    ja: "カテゴリ",
    ko: "분류",
  },
  default: {
    "zh-CN": "最新",
    "zh-TW": "最新",
    en: "Latest",
    ja: "最新",
    ko: "최신",
  },
};

const SUBTYPE_LABEL_OVERRIDES = {
  排行榜: {
    "zh-CN": "排行榜",
    "zh-TW": "排行榜",
    en: "Rankings",
    ja: "ランキング",
    ko: "랭킹",
  },
  "模型周度热度榜": {
    "zh-CN": "模型周度热度榜",
    "zh-TW": "模型週熱度榜",
    en: "Weekly Model Usage Rankings",
    ja: "週間モデル利用ランキング",
    ko: "주간 모델 사용량 랭킹",
  },
  模型周榜: {
    "zh-CN": "模型周榜",
    "zh-TW": "模型週榜",
    en: "Weekly Models",
    ja: "週間モデル",
    ko: "주간 모델",
  },
  厂商份额: {
    "zh-CN": "厂商份额",
    "zh-TW": "廠商份額",
    en: "Provider Share",
    ja: "プロバイダシェア",
    ko: "제공사 점유율",
  },
  多模态输入: {
    "zh-CN": "多模态输入",
    "zh-TW": "多模態輸入",
    en: "Multimodal Input",
    ja: "マルチモーダル入力",
    ko: "멀티모달 입력",
  },
  图像输出: {
    "zh-CN": "图像输出",
    "zh-TW": "圖像輸出",
    en: "Image Output",
    ja: "画像出力",
    ko: "이미지 출력",
  },
  应用日榜: {
    "zh-CN": "应用日榜",
    "zh-TW": "應用日榜",
    en: "Daily Apps",
    ja: "日次アプリ",
    ko: "일간 앱",
  },
  应用周榜: {
    "zh-CN": "应用周榜",
    "zh-TW": "應用週榜",
    en: "Weekly Apps",
    ja: "週間アプリ",
    ko: "주간 앱",
  },
  应用月榜: {
    "zh-CN": "应用月榜",
    "zh-TW": "應用月榜",
    en: "Monthly Apps",
    ja: "月間アプリ",
    ko: "월간 앱",
  },
  性能榜: {
    "zh-CN": "性能榜",
    "zh-TW": "效能榜",
    en: "Performance",
    ja: "性能",
    ko: "성능",
  },
  "AA 智能": {
    "zh-CN": "AA 智能",
    "zh-TW": "AA 智能",
    en: "AA Intelligence",
    ja: "AAインテリジェンス",
    ko: "AA 인텔리전스",
  },
  英文: {
    "zh-CN": "英文",
    "zh-TW": "英文",
    en: "English",
    ja: "英語",
    ko: "영어",
  },
  Python: {
    "zh-CN": "Python",
    "zh-TW": "Python",
    en: "Python",
    ja: "Python",
    ko: "Python",
  },
  "10K 上下文": {
    "zh-CN": "10K 上下文",
    "zh-TW": "10K 上下文",
    en: "10K Context",
    ja: "10Kコンテキスト",
    ko: "10K 컨텍스트",
  },
  "模型综合评测榜": {
    "zh-CN": "模型综合评测榜",
    "zh-TW": "模型綜合評測榜",
    en: "Model Evaluation Rankings",
    ja: "総合モデル評価ランキング",
    ko: "모델 종합 평가 랭킹",
  },
  "模型偏好对战榜": {
    "zh-CN": "模型偏好对战榜",
    "zh-TW": "模型偏好對戰榜",
    en: "Preference Battle Rankings",
    ja: "モデル対戦ランキング",
    ko: "선호도 배틀 랭킹",
  },
  "全球 AI 产品热度榜": {
    "zh-CN": "全球 AI 产品热度榜",
    "zh-TW": "全球 AI 產品熱度榜",
    en: "Global AI Product Rankings",
    ja: "世界AIプロダクト人気ランキング",
    ko: "글로벌 AI 제품 인기 랭킹",
  },
  "排行榜总榜": {
    "zh-CN": "排行榜总榜",
    "zh-TW": "排行榜總榜",
    en: "Overall Rankings",
    ja: "総合ランキング",
    ko: "종합 랭킹",
  },
  "模型性能 / 价格榜": {
    "zh-CN": "模型性能 / 价格榜",
    "zh-TW": "模型效能 / 價格榜",
    en: "Performance & Pricing Rankings",
    ja: "性能・価格ランキング",
    ko: "성능·가격 랭킹",
  },
  "Agent Skills 安装榜": {
    "zh-CN": "Agent Skills 安装榜",
    "zh-TW": "Agent Skills 安裝榜",
    en: "Agent Skills Install Rankings",
    ja: "Agent Skills インストールランキング",
    ko: "Agent Skills 설치 랭킹",
  },
  "技能 / 插件": {
    "zh-CN": "技能 / 插件",
    "zh-TW": "技能 / 外掛",
    en: "Skills / Plugins",
    ja: "スキル / プラグイン",
    ko: "스킬 / 플러그인",
  },
  "Skills 推荐榜": {
    "zh-CN": "技能推荐榜",
    "zh-TW": "技能推薦榜",
    en: "Recommended Skills",
    ja: "おすすめスキル",
    ko: "추천 스킬",
  },
  "Plugins 推荐榜": {
    "zh-CN": "插件推荐榜",
    "zh-TW": "外掛推薦榜",
    en: "Recommended Plugins",
    ja: "おすすめプラグイン",
    ko: "추천 플러그인",
  },
  "WebDev 模型榜": {
    "zh-CN": "WebDev 模型榜",
    "zh-TW": "WebDev 模型榜",
    en: "WebDev Model Rankings",
    ja: "WebDevモデルランキング",
    ko: "WebDev 모델 랭킹",
  },
  "Full-Stack WebDev 模型榜": {
    "zh-CN": "Agentic 全栈应用模型榜",
    "zh-TW": "Agentic 全棧應用模型榜",
    en: "Full-Stack WebDev Model Rankings",
    ja: "Full-Stack WebDevモデルランキング",
    ko: "Full-Stack WebDev 모델 랭킹",
  },
  "Full-Stack WebDev 胜率榜": {
    "zh-CN": "Agentic 全栈应用胜率榜",
    "zh-TW": "Agentic 全棧應用勝率榜",
    en: "Full-Stack WebDev Win Rate Rankings",
    ja: "Full-Stack WebDev勝率ランキング",
    ko: "Full-Stack WebDev 승률 랭킹",
  },
  "Agentic 全栈应用模型榜": {
    "zh-CN": "Agentic 全栈应用模型榜",
    "zh-TW": "Agentic 全棧應用模型榜",
    en: "Agentic Full-Stack App Model Rankings",
    ja: "Agenticフルスタックアプリモデルランキング",
    ko: "Agentic 풀스택 앱 모델 랭킹",
  },
  "Agentic 全栈应用胜率榜": {
    "zh-CN": "Agentic 全栈应用胜率榜",
    "zh-TW": "Agentic 全棧應用勝率榜",
    en: "Agentic Full-Stack App Win Rate Rankings",
    ja: "Agenticフルスタックアプリ勝率ランキング",
    ko: "Agentic 풀스택 앱 승률 랭킹",
  },
  "Agentic Frontend 模型榜": {
    "zh-CN": "Agentic 前端模型榜",
    "zh-TW": "Agentic 前端模型榜",
    en: "Agentic Frontend Model Rankings",
    ja: "Agenticフロントエンドモデルランキング",
    ko: "Agentic 프론트엔드 모델 랭킹",
  },
  "Agentic Frontend 胜率榜": {
    "zh-CN": "Agentic 前端胜率榜",
    "zh-TW": "Agentic 前端勝率榜",
    en: "Agentic Frontend Win Rate Rankings",
    ja: "Agenticフロントエンド勝率ランキング",
    ko: "Agentic 프론트엔드 승률 랭킹",
  },
  "Fullstack App Quality 榜": {
    "zh-CN": "全栈应用质量榜",
    "zh-TW": "全棧應用品質榜",
    en: "Fullstack App Quality",
    ja: "フルスタックアプリ品質ランキング",
    ko: "풀스택 앱 품질 랭킹",
  },
  "全栈应用质量榜": {
    "zh-CN": "全栈应用质量榜",
    "zh-TW": "全棧應用品質榜",
    en: "Fullstack App Quality",
    ja: "フルスタックアプリ品質ランキング",
    ko: "풀스택 앱 품질 랭킹",
  },
  "Backend Scores 榜": {
    "zh-CN": "后端能力评分榜",
    "zh-TW": "後端能力評分榜",
    en: "Backend Scores",
    ja: "バックエンドスコア",
    ko: "백엔드 점수",
  },
  "Daily Usage 榜": {
    "zh-CN": "日活使用榜",
    "zh-TW": "日活使用榜",
    en: "Daily Usage",
    ja: "デイリー利用",
    ko: "일일 사용량",
  },
  "Real-World Reach 榜": {
    "zh-CN": "真实触达榜",
    "zh-TW": "真實觸達榜",
    en: "Real-World Reach",
    ja: "実利用リーチ",
    ko: "실사용 도달",
  },
  "Returning Users 榜": {
    "zh-CN": "回访用户榜",
    "zh-TW": "回訪使用者榜",
    en: "Returning Users",
    ja: "リピート利用者",
    ko: "재방문 사용자",
  },
  "App Downloads 榜": {
    "zh-CN": "应用下载榜",
    "zh-TW": "應用下載榜",
    en: "App Downloads",
    ja: "アプリダウンロード",
    ko: "앱 다운로드",
  },
  "Website 模型榜": {
    "zh-CN": "网站模型榜",
    "zh-TW": "網站模型榜",
    en: "Website Model Rankings",
    ja: "Webサイトモデルランキング",
    ko: "웹사이트 모델 랭킹",
  },
  "Website 胜率榜": {
    "zh-CN": "网站胜率榜",
    "zh-TW": "網站勝率榜",
    en: "Website Win Rate Rankings",
    ja: "Webサイト勝率ランキング",
    ko: "웹사이트 승률 랭킹",
  },
  "UI Component 模型榜": {
    "zh-CN": "UI 组件模型榜",
    "zh-TW": "UI 元件模型榜",
    en: "UI Component Model Rankings",
    ja: "UIコンポーネントモデルランキング",
    ko: "UI 컴포넌트 모델 랭킹",
  },
  "Data Visualization 模型榜": {
    "zh-CN": "数据可视化模型榜",
    "zh-TW": "資料視覺化模型榜",
    en: "Data Visualization Model Rankings",
    ja: "データ可視化モデルランキング",
    ko: "데이터 시각화 모델 랭킹",
  },
  "SVG 模型榜": {
    "zh-CN": "SVG 模型榜",
    "zh-TW": "SVG 模型榜",
    en: "SVG Model Rankings",
    ja: "SVGモデルランキング",
    ko: "SVG 모델 랭킹",
  },
  "ASCII Art 模型榜": {
    "zh-CN": "ASCII Art 模型榜",
    "zh-TW": "ASCII Art 模型榜",
    en: "ASCII Art Model Rankings",
    ja: "ASCII Artモデルランキング",
    ko: "ASCII Art 모델 랭킹",
  },
  "Game Dev 模型榜": {
    "zh-CN": "游戏开发模型榜",
    "zh-TW": "遊戲開發模型榜",
    en: "Game Dev Model Rankings",
    ja: "ゲーム開発モデルランキング",
    ko: "게임 개발 모델 랭킹",
  },
  "Agentic 游戏开发模型榜": {
    "zh-CN": "Agentic 游戏开发模型榜",
    "zh-TW": "Agentic 遊戲開發模型榜",
    en: "Agentic Game Dev Model Rankings",
    ja: "Agenticゲーム開発モデルランキング",
    ko: "Agentic 게임 개발 모델 랭킹",
  },
  "移动 App 模型榜": {
    "zh-CN": "移动 App 模型榜",
    "zh-TW": "行動 App 模型榜",
    en: "Mobile App Model Rankings",
    ja: "モバイルAppモデルランキング",
    ko: "모바일 앱 모델 랭킹",
  },
  "原生 App 模型榜": {
    "zh-CN": "原生 App 模型榜",
    "zh-TW": "原生 App 模型榜",
    en: "Native App Model Rankings",
    ja: "ネイティブAppモデルランキング",
    ko: "네이티브 앱 모델 랭킹",
  },
  "3D Design 模型榜": {
    "zh-CN": "3D 设计模型榜",
    "zh-TW": "3D 設計模型榜",
    en: "3D Design Model Rankings",
    ja: "3Dデザインモデルランキング",
    ko: "3D 디자인 모델 랭킹",
  },
  "Slides 模型榜": {
    "zh-CN": "演示文稿模型榜",
    "zh-TW": "簡報模型榜",
    en: "Slides Model Rankings",
    ja: "スライドモデルランキング",
    ko: "슬라이드 모델 랭킹",
  },
  "Agentic Slides 模型榜": {
    "zh-CN": "Agentic 演示文稿模型榜",
    "zh-TW": "Agentic 簡報模型榜",
    en: "Agentic Slides Model Rankings",
    ja: "Agenticスライドモデルランキング",
    ko: "Agentic 슬라이드 모델 랭킹",
  },
  "Agentic HTML Slides 模型榜": {
    "zh-CN": "Agentic HTML 演示文稿模型榜",
    "zh-TW": "Agentic HTML 簡報模型榜",
    en: "Agentic HTML Slides Model Rankings",
    ja: "Agentic HTMLスライドモデルランキング",
    ko: "Agentic HTML 슬라이드 모델 랭킹",
  },
  "Image Generation 模型榜": {
    "zh-CN": "图像生成模型榜",
    "zh-TW": "圖像生成模型榜",
    en: "Image Generation Model Rankings",
    ja: "画像生成モデルランキング",
    ko: "이미지 생성 모델 랭킹",
  },
  "Image Editing 模型榜": {
    "zh-CN": "图像编辑模型榜",
    "zh-TW": "圖像編輯模型榜",
    en: "Image Editing Model Rankings",
    ja: "画像編集モデルランキング",
    ko: "이미지 편집 모델 랭킹",
  },
  "Graphic Design 模型榜": {
    "zh-CN": "平面设计模型榜",
    "zh-TW": "平面設計模型榜",
    en: "Graphic Design Model Rankings",
    ja: "グラフィックデザインモデルランキング",
    ko: "그래픽 디자인 모델 랭킹",
  },
  "Logo 模型榜": {
    "zh-CN": "Logo 模型榜",
    "zh-TW": "Logo 模型榜",
    en: "Logo Model Rankings",
    ja: "Logoモデルランキング",
    ko: "Logo 모델 랭킹",
  },
  "Video 模型榜": {
    "zh-CN": "视频模型榜",
    "zh-TW": "影片模型榜",
    en: "Video Model Rankings",
    ja: "動画モデルランキング",
    ko: "비디오 모델 랭킹",
  },
  "Video Editing 模型榜": {
    "zh-CN": "视频编辑模型榜",
    "zh-TW": "影片編輯模型榜",
    en: "Video Editing Model Rankings",
    ja: "動画編集モデルランキング",
    ko: "비디오 편집 모델 랭킹",
  },
  "Image to Video 模型榜": {
    "zh-CN": "图像转视频模型榜",
    "zh-TW": "圖像轉影片模型榜",
    en: "Image to Video Model Rankings",
    ja: "画像から動画モデルランキング",
    ko: "이미지 비디오 모델 랭킹",
  },
  "Multi to Video 模型榜": {
    "zh-CN": "多输入转视频模型榜",
    "zh-TW": "多輸入轉影片模型榜",
    en: "Multi to Video Model Rankings",
    ja: "マルチ入力動画モデルランキング",
    ko: "멀티 입력 비디오 모델 랭킹",
  },
  "Multimodal to Video 模型榜": {
    "zh-CN": "多模态转视频模型榜",
    "zh-TW": "多模態轉影片模型榜",
    en: "Multimodal to Video Model Rankings",
    ja: "マルチモーダル動画モデルランキング",
    ko: "멀티모달 비디오 모델 랭킹",
  },
  "TTS 模型榜": {
    "zh-CN": "TTS 模型榜",
    "zh-TW": "TTS 模型榜",
    en: "TTS Model Rankings",
    ja: "TTSモデルランキング",
    ko: "TTS 모델 랭킹",
  },
  "AI Builder 榜": {
    "zh-CN": "AI 构建器榜",
    "zh-TW": "AI 建構器榜",
    en: "AI Builder Rankings",
    ja: "AIビルダーランキング",
    ko: "AI 빌더 랭킹",
  },
  后端能力评分榜: {
    "zh-CN": "后端能力评分榜",
    "zh-TW": "後端能力評分榜",
    en: "Backend Scores",
    ja: "バックエンドスコア",
    ko: "백엔드 점수",
  },
  日活使用榜: {
    "zh-CN": "日活使用榜",
    "zh-TW": "日活使用榜",
    en: "Daily Usage",
    ja: "デイリー利用",
    ko: "일일 사용량",
  },
  真实触达榜: {
    "zh-CN": "真实触达榜",
    "zh-TW": "真實觸達榜",
    en: "Real-World Reach",
    ja: "実利用リーチ",
    ko: "실사용 도달",
  },
  回访用户榜: {
    "zh-CN": "回访用户榜",
    "zh-TW": "回訪使用者榜",
    en: "Returning Users",
    ja: "リピート利用者",
    ko: "재방문 사용자",
  },
  应用下载榜: {
    "zh-CN": "应用下载榜",
    "zh-TW": "應用下載榜",
    en: "App Downloads",
    ja: "アプリダウンロード",
    ko: "앱 다운로드",
  },
  网站模型榜: {
    "zh-CN": "网站模型榜",
    "zh-TW": "網站模型榜",
    en: "Website Model Rankings",
    ja: "Webサイトモデルランキング",
    ko: "웹사이트 모델 랭킹",
  },
  网站胜率榜: {
    "zh-CN": "网站胜率榜",
    "zh-TW": "網站勝率榜",
    en: "Website Win Rate Rankings",
    ja: "Webサイト勝率ランキング",
    ko: "웹사이트 승률 랭킹",
  },
  "UI 组件模型榜": {
    "zh-CN": "UI 组件模型榜",
    "zh-TW": "UI 元件模型榜",
    en: "UI Component Model Rankings",
    ja: "UIコンポーネントモデルランキング",
    ko: "UI 컴포넌트 모델 랭킹",
  },
  数据可视化模型榜: {
    "zh-CN": "数据可视化模型榜",
    "zh-TW": "資料視覺化模型榜",
    en: "Data Visualization Model Rankings",
    ja: "データ可視化モデルランキング",
    ko: "데이터 시각화 모델 랭킹",
  },
  游戏开发模型榜: {
    "zh-CN": "游戏开发模型榜",
    "zh-TW": "遊戲開發模型榜",
    en: "Game Dev Model Rankings",
    ja: "ゲーム開発モデルランキング",
    ko: "게임 개발 모델 랭킹",
  },
  "3D 设计模型榜": {
    "zh-CN": "3D 设计模型榜",
    "zh-TW": "3D 設計模型榜",
    en: "3D Design Model Rankings",
    ja: "3Dデザインモデルランキング",
    ko: "3D 디자인 모델 랭킹",
  },
  演示文稿模型榜: {
    "zh-CN": "演示文稿模型榜",
    "zh-TW": "簡報模型榜",
    en: "Slides Model Rankings",
    ja: "スライドモデルランキング",
    ko: "슬라이드 모델 랭킹",
  },
  图像生成模型榜: {
    "zh-CN": "图像生成模型榜",
    "zh-TW": "圖像生成模型榜",
    en: "Image Generation Model Rankings",
    ja: "画像生成モデルランキング",
    ko: "이미지 생성 모델 랭킹",
  },
  图像编辑模型榜: {
    "zh-CN": "图像编辑模型榜",
    "zh-TW": "圖像編輯模型榜",
    en: "Image Editing Model Rankings",
    ja: "画像編集モデルランキング",
    ko: "이미지 편집 모델 랭킹",
  },
  平面设计模型榜: {
    "zh-CN": "平面设计模型榜",
    "zh-TW": "平面設計模型榜",
    en: "Graphic Design Model Rankings",
    ja: "グラフィックデザインモデルランキング",
    ko: "그래픽 디자인 모델 랭킹",
  },
  视频生成模型榜: {
    "zh-CN": "视频生成模型榜",
    "zh-TW": "影片生成模型榜",
    en: "Video Generation Model Rankings",
    ja: "動画生成モデルランキング",
    ko: "비디오 생성 모델 랭킹",
  },
  视频编辑模型榜: {
    "zh-CN": "视频编辑模型榜",
    "zh-TW": "影片編輯模型榜",
    en: "Video Editing Model Rankings",
    ja: "動画編集モデルランキング",
    ko: "비디오 편집 모델 랭킹",
  },
  图像转视频模型榜: {
    "zh-CN": "图像转视频模型榜",
    "zh-TW": "圖像轉影片模型榜",
    en: "Image to Video Model Rankings",
    ja: "画像から動画モデルランキング",
    ko: "이미지 비디오 모델 랭킹",
  },
  多输入转视频模型榜: {
    "zh-CN": "多输入转视频模型榜",
    "zh-TW": "多輸入轉影片模型榜",
    en: "Multi to Video Model Rankings",
    ja: "マルチ入力動画モデルランキング",
    ko: "멀티 입력 비디오 모델 랭킹",
  },
  多模态转视频模型榜: {
    "zh-CN": "多模态转视频模型榜",
    "zh-TW": "多模態轉影片模型榜",
    en: "Multimodal to Video Model Rankings",
    ja: "マルチモーダル動画モデルランキング",
    ko: "멀티모달 비디오 모델 랭킹",
  },
  "AI 构建器榜": {
    "zh-CN": "AI 构建器榜",
    "zh-TW": "AI 建構器榜",
    en: "AI Builder Rankings",
    ja: "AIビルダーランキング",
    ko: "AI 빌더 랭킹",
  },
  "Agentic 前端模型榜": {
    "zh-CN": "Agentic 前端模型榜",
    "zh-TW": "Agentic 前端模型榜",
    en: "Agentic Frontend Model Rankings",
    ja: "Agenticフロントエンドモデルランキング",
    ko: "Agentic 프론트엔드 모델 랭킹",
  },
  "Agentic 前端胜率榜": {
    "zh-CN": "Agentic 前端胜率榜",
    "zh-TW": "Agentic 前端勝率榜",
    en: "Agentic Frontend Win Rate Rankings",
    ja: "Agenticフロントエンド勝率ランキング",
    ko: "Agentic 프론트엔드 승률 랭킹",
  },
  "Agentic 演示文稿模型榜": {
    "zh-CN": "Agentic 演示文稿模型榜",
    "zh-TW": "Agentic 簡報模型榜",
    en: "Agentic Slides Model Rankings",
    ja: "Agenticスライドモデルランキング",
    ko: "Agentic 슬라이드 모델 랭킹",
  },
  "Agentic HTML 演示文稿模型榜": {
    "zh-CN": "Agentic HTML 演示文稿模型榜",
    "zh-TW": "Agentic HTML 簡報模型榜",
    en: "Agentic HTML Slides Model Rankings",
    ja: "Agentic HTMLスライドモデルランキング",
    ko: "Agentic HTML 슬라이드 모델 랭킹",
  },
  官方资讯: {
    "zh-CN": "官方资讯",
    "zh-TW": "官方資訊",
    en: "Official Updates",
    ja: "公式情報",
    ko: "공식 업데이트",
  },
  官方新闻: {
    "zh-CN": "官方新闻",
    "zh-TW": "官方新聞",
    en: "Official News",
    ja: "公式ニュース",
    ko: "공식 뉴스",
  },
  "官方研究": {
    "zh-CN": "官方研究",
    "zh-TW": "官方研究",
    en: "Official Research",
    ja: "公式研究",
    ko: "공식 연구",
  },
  "官方研究更新": {
    "zh-CN": "官方研究",
    "zh-TW": "官方研究",
    en: "Official Research",
    ja: "公式研究",
    ko: "공식 연구",
  },
  官方博客: {
    "zh-CN": "官方博客",
    "zh-TW": "官方部落格",
    en: "Official Blog",
    ja: "公式ブログ",
    ko: "공식 블로그",
  },
  "官方 AI 动态": {
    "zh-CN": "官方 AI 动态",
    "zh-TW": "官方 AI 動態",
    en: "Official AI Updates",
    ja: "公式AIアップデート",
    ko: "공식 AI 업데이트",
  },
  "开源模型趋势榜": {
    "zh-CN": "开源模型趋势榜",
    "zh-TW": "開源模型趨勢榜",
    en: "Open Model Rankings",
    ja: "オープンモデル人気ランキング",
    ko: "오픈 모델 트렌드 랭킹",
  },
  "热门论文趋势榜": {
    "zh-CN": "热门论文趋势榜",
    "zh-TW": "熱門論文趨勢榜",
    en: "Trending Papers Rankings",
    ja: "注目論文ランキング",
    ko: "인기 논문 트렌드 랭킹",
  },
  论文榜: {
    "zh-CN": "论文榜",
    "zh-TW": "論文榜",
    en: "Papers",
    ja: "論文",
    ko: "논문",
  },
  日榜: {
    "zh-CN": "日榜",
    "zh-TW": "日榜",
    en: "Daily Rankings",
    ja: "日間ランキング",
    ko: "일간 랭킹",
  },
  周榜: {
    "zh-CN": "周榜",
    "zh-TW": "週榜",
    en: "Weekly Rankings",
    ja: "週間ランキング",
    ko: "주간 랭킹",
  },
  "开放模型总榜": {
    "zh-CN": "开放模型总榜",
    "zh-TW": "開放模型總榜",
    en: "Open Model Rankings",
    ja: "オープンモデル総合",
    ko: "오픈 모델 종합",
  },
  "编程能力榜": {
    "zh-CN": "编程能力榜",
    "zh-TW": "程式能力榜",
    en: "Coding Rankings",
    ja: "コーディングランキング",
    ko: "코딩 랭킹",
  },
  "写作能力榜": {
    "zh-CN": "写作能力榜",
    "zh-TW": "寫作能力榜",
    en: "Writing Rankings",
    ja: "ライティングランキング",
    ko: "글쓰기 랭킹",
  },
  "数学能力榜": {
    "zh-CN": "数学能力榜",
    "zh-TW": "數學能力榜",
    en: "Math Rankings",
    ja: "数学ランキング",
    ko: "수학 랭킹",
  },
  "研究能力榜": {
    "zh-CN": "研究能力榜",
    "zh-TW": "研究能力榜",
    en: "Research Rankings",
    ja: "研究ランキング",
    ko: "연구 랭킹",
  },
  "长上下文榜": {
    "zh-CN": "长上下文榜",
    "zh-TW": "長上下文榜",
    en: "Long Context Rankings",
    ja: "長文脈ランキング",
    ko: "롱컨텍스트 랭킹",
  },
  "工具调用榜": {
    "zh-CN": "工具调用榜",
    "zh-TW": "工具調用榜",
    en: "Tool Calling Rankings",
    ja: "ツール利用ランキング",
    ko: "툴콜링 랭킹",
  },
  "推理能力榜": {
    "zh-CN": "推理能力榜",
    "zh-TW": "推理能力榜",
    en: "Reasoning Rankings",
    ja: "推論ランキング",
    ko: "추론 랭킹",
  },
  "图像生成榜": {
    "zh-CN": "图像生成榜",
    "zh-TW": "圖像生成榜",
    en: "Image Generation Rankings",
    ja: "画像生成ランキング",
    ko: "이미지 생성 랭킹",
  },
  图像生成: {
    "zh-CN": "图像生成",
    "zh-TW": "圖像生成",
    en: "Image Generation",
    ja: "画像生成",
    ko: "이미지 생성",
  },
  "视频生成榜": {
    "zh-CN": "视频生成榜",
    "zh-TW": "影片生成榜",
    en: "Video Generation Rankings",
    ja: "動画生成ランキング",
    ko: "비디오 생성 랭킹",
  },
  "模型厂商榜": {
    "zh-CN": "模型厂商榜",
    "zh-TW": "模型廠商榜",
    en: "Provider Rankings",
    ja: "プロバイダランキング",
    ko: "프로바이더 랭킹",
  },
  "全球网站热度榜": {
    "zh-CN": "全球网站热度榜",
    "zh-TW": "全球網站熱度榜",
    en: "Global Website Rankings",
    ja: "グローバルWebランキング",
    ko: "글로벌 웹 랭킹",
  },
  "全球 App 热度榜": {
    "zh-CN": "全球 App 热度榜",
    "zh-TW": "全球 App 熱度榜",
    en: "Global App Rankings",
    ja: "グローバルAppランキング",
    ko: "글로벌 앱 랭킹",
  },
  "中国 AI 热度榜": {
    "zh-CN": "中国 AI 热度榜",
    "zh-TW": "中國 AI 熱度榜",
    en: "China AI Rankings",
    ja: "中国AIランキング",
    ko: "중국 AI 랭킹",
  },
  "AI ChatBot 热度榜": {
    "zh-CN": "AI ChatBot 热度榜",
    "zh-TW": "AI ChatBot 熱度榜",
    en: "AI Chatbot Rankings",
    ja: "AIチャットボットランキング",
    ko: "AI 챗봇 랭킹",
  },
  "AI Search 热度榜": {
    "zh-CN": "AI Search 热度榜",
    "zh-TW": "AI Search 熱度榜",
    en: "AI Search Rankings",
    ja: "AI検索ランキング",
    ko: "AI 검색 랭킹",
  },
  "AI Vibe Coding 热度榜": {
    "zh-CN": "AI Vibe Coding 热度榜",
    "zh-TW": "AI Vibe Coding 熱度榜",
    en: "AI Vibe Coding Rankings",
    ja: "AI Vibe Codingランキング",
    ko: "AI Vibe Coding 랭킹",
  },
  "AI Agent 热度榜": {
    "zh-CN": "AI Agent 热度榜",
    "zh-TW": "AI Agent 熱度榜",
    en: "AI Agent Rankings",
    ja: "AIエージェントランキング",
    ko: "AI 에이전트 랭킹",
  },
  "Claw Agent 热度榜": {
    "zh-CN": "Claw Agent 热度榜",
    "zh-TW": "Claw Agent 熱度榜",
    en: "Claw Agent Rankings",
    ja: "Claw Agentランキング",
    ko: "Claw Agent 랭킹",
  },
  "AI Character 热度榜": {
    "zh-CN": "AI Character 热度榜",
    "zh-TW": "AI Character 熱度榜",
    en: "AI Character Rankings",
    ja: "AIキャラクターランキング",
    ko: "AI 캐릭터 랭킹",
  },
  "AI Image Generator 热度榜": {
    "zh-CN": "AI Image Generator 热度榜",
    "zh-TW": "AI Image Generator 熱度榜",
    en: "AI Image Generator Rankings",
    ja: "AI画像生成ランキング",
    ko: "AI 이미지 생성 랭킹",
  },
  "AI Image Editor 热度榜": {
    "zh-CN": "AI Image Editor 热度榜",
    "zh-TW": "AI Image Editor 熱度榜",
    en: "AI Image Editor Rankings",
    ja: "AI画像編集ランキング",
    ko: "AI 이미지 편집 랭킹",
  },
  "AI Video Generator 热度榜": {
    "zh-CN": "AI Video Generator 热度榜",
    "zh-TW": "AI Video Generator 熱度榜",
    en: "AI Video Generator Rankings",
    ja: "AI動画生成ランキング",
    ko: "AI 비디오 생성 랭킹",
  },
  "AI Video Editor 热度榜": {
    "zh-CN": "AI Video Editor 热度榜",
    "zh-TW": "AI Video Editor 熱度榜",
    en: "AI Video Editor Rankings",
    ja: "AI動画編集ランキング",
    ko: "AI 비디오 편집 랭킹",
  },
  "AI PPT 热度榜": {
    "zh-CN": "AI PPT 热度榜",
    "zh-TW": "AI PPT 熱度榜",
    en: "AI PPT Rankings",
    ja: "AIプレゼンランキング",
    ko: "AI PPT 랭킹",
  },
  "AI Music 热度榜": {
    "zh-CN": "AI Music 热度榜",
    "zh-TW": "AI Music 熱度榜",
    en: "AI Music Rankings",
    ja: "AI音楽ランキング",
    ko: "AI 음악 랭킹",
  },
  "AI Meeting 热度榜": {
    "zh-CN": "AI Meeting 热度榜",
    "zh-TW": "AI Meeting 熱度榜",
    en: "AI Meeting Rankings",
    ja: "AI会議ランキング",
    ko: "AI 미팅 랭킹",
  },
  "AI Cloud 热度榜": {
    "zh-CN": "AI Cloud 热度榜",
    "zh-TW": "AI Cloud 熱度榜",
    en: "AI Cloud Rankings",
    ja: "AIクラウドランキング",
    ko: "AI 클라우드 랭킹",
  },
  "全球增长榜": {
    "zh-CN": "全球增长榜",
    "zh-TW": "全球增長榜",
    en: "Global Growth Rankings",
    ja: "グローバル成長ランキング",
    ko: "글로벌 성장 랭킹",
  },
  "中国增长榜": {
    "zh-CN": "中国增长榜",
    "zh-TW": "中國增長榜",
    en: "China Growth Rankings",
    ja: "中国成長ランキング",
    ko: "중국 성장 랭킹",
  },
  "Claw 增长榜": {
    "zh-CN": "Claw 增长榜",
    "zh-TW": "Claw 增長榜",
    en: "Claw Growth Rankings",
    ja: "Claw成長ランキング",
    ko: "Claw 성장 랭킹",
  },
  "全球放缓榜": {
    "zh-CN": "全球放缓榜",
    "zh-TW": "全球放緩榜",
    en: "Global Slowdown Rankings",
    ja: "グローバル減速ランキング",
    ko: "글로벌 둔화 랭킹",
  },
  "综合对话榜": {
    "zh-CN": "综合对话榜",
    "zh-TW": "綜合對話榜",
    en: "Overall Chat Rankings",
    ja: "総合チャットランキング",
    ko: "종합 채팅 랭킹",
  },
  "Agent 对战榜": {
    "zh-CN": "Agent 对战榜",
    "zh-TW": "Agent 對戰榜",
    en: "Agent Rankings",
    ja: "Agentランキング",
    ko: "Agent 랭킹",
  },
  "WebDev 对战榜": {
    "zh-CN": "WebDev 对战榜",
    "zh-TW": "WebDev 對戰榜",
    en: "WebDev Rankings",
    ja: "WebDevランキング",
    ko: "WebDev 랭킹",
  },
  "HTML WebDev 榜": {
    "zh-CN": "HTML WebDev 榜",
    "zh-TW": "HTML WebDev 榜",
    en: "HTML WebDev Rankings",
    ja: "HTML WebDevランキング",
    ko: "HTML WebDev 랭킹",
  },
  "React WebDev 榜": {
    "zh-CN": "React WebDev 榜",
    "zh-TW": "React WebDev 榜",
    en: "React WebDev Rankings",
    ja: "React WebDevランキング",
    ko: "React WebDev 랭킹",
  },
  "Image to WebDev 榜": {
    "zh-CN": "Image to WebDev 榜",
    "zh-TW": "Image to WebDev 榜",
    en: "Image to WebDev Rankings",
    ja: "Image to WebDevランキング",
    ko: "Image to WebDev 랭킹",
  },
  "Text to Image 榜": {
    "zh-CN": "Text to Image 榜",
    "zh-TW": "Text to Image 榜",
    en: "Text to Image Rankings",
    ja: "Text to Imageランキング",
    ko: "Text to Image 랭킹",
  },
  "Image Edit 榜": {
    "zh-CN": "Image Edit 榜",
    "zh-TW": "Image Edit 榜",
    en: "Image Edit Rankings",
    ja: "Image Editランキング",
    ko: "Image Edit 랭킹",
  },
  "Text to Video 榜": {
    "zh-CN": "Text to Video 榜",
    "zh-TW": "Text to Video 榜",
    en: "Text to Video Rankings",
    ja: "Text to Videoランキング",
    ko: "Text to Video 랭킹",
  },
  "Image to Video 榜": {
    "zh-CN": "Image to Video 榜",
    "zh-TW": "Image to Video 榜",
    en: "Image to Video Rankings",
    ja: "Image to Videoランキング",
    ko: "Image to Video 랭킹",
  },
  "Video Edit 榜": {
    "zh-CN": "Video Edit 榜",
    "zh-TW": "Video Edit 榜",
    en: "Video Edit Rankings",
    ja: "Video Editランキング",
    ko: "Video Edit 랭킹",
  },
  "Vision 对战榜": {
    "zh-CN": "Vision 对战榜",
    "zh-TW": "Vision 對戰榜",
    en: "Vision Rankings",
    ja: "Visionランキング",
    ko: "Vision 랭킹",
  },
  "Document 对战榜": {
    "zh-CN": "Document 对战榜",
    "zh-TW": "Document 對戰榜",
    en: "Document Rankings",
    ja: "Documentランキング",
    ko: "Document 랭킹",
  },
  "Search 对战榜": {
    "zh-CN": "Search 对战榜",
    "zh-TW": "Search 對戰榜",
    en: "Search Rankings",
    ja: "Searchランキング",
    ko: "Search 랭킹",
  },
  "论文代码镜像榜": {
    "zh-CN": "论文代码镜像榜",
    "zh-TW": "論文程式碼鏡像榜",
    en: "Paper-Code Mirror Rankings",
    ja: "論文コードミラーランキング",
    ko: "논문·코드 미러 랭킹",
  },
  产品发现: {
    "zh-CN": "产品发现",
    "zh-TW": "產品發現",
    en: "Product Discovery",
    ja: "プロダクト発見",
    ko: "제품 발견",
  },
  "AI 新品发现": {
    "zh-CN": "AI 新品发现",
    "zh-TW": "AI 新品發現",
    en: "AI Product Discovery",
    ja: "AI新製品発見",
    ko: "AI 신제품 발견",
  },
  社区热议: {
    "zh-CN": "社区热议",
    "zh-TW": "社群熱議",
    en: "Community Discussions",
    ja: "コミュニティ議論",
    ko: "커뮤니티 토론",
  },
  "AI 热门讨论": {
    "zh-CN": "AI 热门讨论",
    "zh-TW": "AI 熱門討論",
    en: "AI Discussions",
    ja: "AI人気議論",
    ko: "AI 인기 토론",
  },
  "中文 AI 资讯热榜": {
    "zh-CN": "中文 AI 资讯热榜",
    "zh-TW": "中文 AI 資訊熱榜",
    en: "Chinese AI News Rankings",
    ja: "中国語AIニュースランキング",
    ko: "중국어 AI 뉴스 랭킹",
  },
  日榜: {
    "zh-CN": "日榜",
    "zh-TW": "日榜",
    en: "Daily",
    ja: "日次",
    ko: "일간",
  },
  周榜: {
    "zh-CN": "周榜",
    "zh-TW": "週榜",
    en: "Weekly",
    ja: "週間",
    ko: "주간",
  },
  热评榜: {
    "zh-CN": "热评榜",
    "zh-TW": "熱評榜",
    en: "Top Comments",
    ja: "人気コメント",
    ko: "인기 댓글",
  },
  月榜: {
    "zh-CN": "月榜",
    "zh-TW": "月榜",
    en: "Monthly",
    ja: "月間",
    ko: "월간",
  },
  Recommended: {
    "zh-CN": "推荐",
    "zh-TW": "推薦",
    en: "Recommended",
    ja: "おすすめ",
    ko: "추천",
  },
  "Recommended Skills": {
    "zh-CN": "推荐技能榜",
    "zh-TW": "推薦技能榜",
    en: "Recommended Skills",
    ja: "おすすめスキル",
    ko: "추천 스킬",
  },
  "Recommended Plugins": {
    "zh-CN": "推荐插件榜",
    "zh-TW": "推薦外掛榜",
    en: "Recommended Plugins",
    ja: "おすすめプラグイン",
    ko: "추천 플러그인",
  },
  Featured: {
    "zh-CN": "精选",
    "zh-TW": "精選",
    en: "Featured",
    ja: "注目",
    ko: "추천작",
  },
  "Featured Skills": {
    "zh-CN": "精选技能榜",
    "zh-TW": "精選技能榜",
    en: "Featured Skills",
    ja: "注目スキル",
    ko: "주요 스킬",
  },
  "Featured Plugins": {
    "zh-CN": "精选插件榜",
    "zh-TW": "精選外掛榜",
    en: "Featured Plugins",
    ja: "注目プラグイン",
    ko: "주요 플러그인",
  },
  "Most starred": {
    "zh-CN": "星标最多",
    "zh-TW": "星標最多",
    en: "Most starred",
    ja: "最多スター",
    ko: "최다 스타",
  },
  "Most starred Skills": {
    "zh-CN": "星标最多技能榜",
    "zh-TW": "星標最多技能榜",
    en: "Most starred Skills",
    ja: "スター最多スキル",
    ko: "스타 최다 스킬",
  },
  "Most installed": {
    "zh-CN": "安装最多",
    "zh-TW": "安裝最多",
    en: "Most installed",
    ja: "最多インストール",
    ko: "최다 설치",
  },
  "Most installed Skills": {
    "zh-CN": "安装最多技能榜",
    "zh-TW": "安裝最多技能榜",
    en: "Most installed Skills",
    ja: "インストール最多スキル",
    ko: "설치 최다 스킬",
  },
  "Most installed Plugins": {
    "zh-CN": "安装最多插件榜",
    "zh-TW": "安裝最多外掛榜",
    en: "Most installed Plugins",
    ja: "インストール最多プラグイン",
    ko: "설치 최다 플러그인",
  },
  "Recently updated": {
    "zh-CN": "最近更新",
    "zh-TW": "最近更新",
    en: "Recently updated",
    ja: "最近更新",
    ko: "최근 업데이트",
  },
  "Recently updated Skills": {
    "zh-CN": "最近更新技能榜",
    "zh-TW": "最近更新技能榜",
    en: "Recently updated Skills",
    ja: "最近更新スキル",
    ko: "최근 업데이트 스킬",
  },
  "Recently updated Plugins": {
    "zh-CN": "最近更新插件榜",
    "zh-TW": "最近更新外掛榜",
    en: "Recently updated Plugins",
    ja: "最近更新プラグイン",
    ko: "최근 업데이트 플러그인",
  },
  Newest: {
    "zh-CN": "最新发布",
    "zh-TW": "最新發布",
    en: "Newest",
    ja: "最新",
    ko: "최신",
  },
  "Newest Skills": {
    "zh-CN": "最新发布技能榜",
    "zh-TW": "最新發布技能榜",
    en: "Newest Skills",
    ja: "最新スキル",
    ko: "최신 스킬",
  },
  Name: {
    "zh-CN": "名称",
    "zh-TW": "名稱",
    en: "Name",
    ja: "名前",
    ko: "이름",
  },
  "Skill Name Index": {
    "zh-CN": "技能名称索引",
    "zh-TW": "技能名稱索引",
    en: "Skill Name Index",
    ja: "スキル名インデックス",
    ko: "스킬 이름 색인",
  },
  "MCP Tools": {
    "zh-CN": "MCP 工具",
    "zh-TW": "MCP 工具",
    en: "MCP Tools",
    ja: "MCP ツール",
    ko: "MCP 도구",
  },
  "MCP Tool Skills": {
    "zh-CN": "MCP 工具技能分类",
    "zh-TW": "MCP 工具技能分類",
    en: "MCP Tool Skills",
    ja: "MCP ツールスキル",
    ko: "MCP 도구 스킬",
  },
  Prompts: {
    "zh-CN": "提示词",
    "zh-TW": "提示詞",
    en: "Prompts",
    ja: "プロンプト",
    ko: "프롬프트",
  },
  "Prompt Skills": {
    "zh-CN": "提示词技能分类",
    "zh-TW": "提示詞技能分類",
    en: "Prompt Skills",
    ja: "プロンプトスキル",
    ko: "프롬프트 스킬",
  },
  Workflows: {
    "zh-CN": "工作流",
    "zh-TW": "工作流",
    en: "Workflows",
    ja: "ワークフロー",
    ko: "워크플로",
  },
  "Workflow Skills": {
    "zh-CN": "工作流技能分类",
    "zh-TW": "工作流技能分類",
    en: "Workflow Skills",
    ja: "ワークフロースキル",
    ko: "워크플로 스킬",
  },
  "Dev Tools": {
    "zh-CN": "开发工具",
    "zh-TW": "開發工具",
    en: "Dev Tools",
    ja: "開発ツール",
    ko: "개발 도구",
  },
  "Developer Tool Skills": {
    "zh-CN": "开发工具技能分类",
    "zh-TW": "開發工具技能分類",
    en: "Developer Tool Skills",
    ja: "開発ツールスキル",
    ko: "개발 도구 스킬",
  },
  "Data & APIs": {
    "zh-CN": "数据与 API",
    "zh-TW": "資料與 API",
    en: "Data & APIs",
    ja: "データと API",
    ko: "데이터와 API",
  },
  "Data & API Skills": {
    "zh-CN": "数据与 API 技能分类",
    "zh-TW": "資料與 API 技能分類",
    en: "Data & API Skills",
    ja: "データと API スキル",
    ko: "데이터와 API 스킬",
  },
  "Data & API Plugins": {
    "zh-CN": "数据与 API 插件分类",
    "zh-TW": "資料與 API 外掛分類",
    en: "Data & API Plugins",
    ja: "データと API プラグイン",
    ko: "데이터와 API 플러그인",
  },
  Security: {
    "zh-CN": "安全",
    "zh-TW": "安全",
    en: "Security",
    ja: "セキュリティ",
    ko: "보안",
  },
  "Security Skills": {
    "zh-CN": "安全技能分类",
    "zh-TW": "安全技能分類",
    en: "Security Skills",
    ja: "セキュリティスキル",
    ko: "보안 스킬",
  },
  Automation: {
    "zh-CN": "自动化",
    "zh-TW": "自動化",
    en: "Automation",
    ja: "自動化",
    ko: "자동화",
  },
  "Automation Skills": {
    "zh-CN": "自动化技能分类",
    "zh-TW": "自動化技能分類",
    en: "Automation Skills",
    ja: "自動化スキル",
    ko: "자동화 스킬",
  },
  Other: {
    "zh-CN": "其他",
    "zh-TW": "其他",
    en: "Other",
    ja: "その他",
    ko: "기타",
  },
  "Other Skills": {
    "zh-CN": "其他技能分类",
    "zh-TW": "其他技能分類",
    en: "Other Skills",
    ja: "その他のスキル",
    ko: "기타 스킬",
  },
  Chat: {
    "zh-CN": "对话",
    "zh-TW": "對話",
    en: "Chat",
    ja: "対話",
    ko: "채팅",
  },
  "Full-Stack ELO": {
    "zh-CN": "全栈 ELO",
    "zh-TW": "全棧 ELO",
    en: "Full-Stack ELO",
    ja: "フルスタックELO",
    ko: "풀스택 ELO",
  },
  "Full-Stack Win Rate": {
    "zh-CN": "全栈胜率",
    "zh-TW": "全棧勝率",
    en: "Full-Stack Win Rate",
    ja: "フルスタック勝率",
    ko: "풀스택 승률",
  },
  "Frontend ELO": {
    "zh-CN": "前端 ELO",
    "zh-TW": "前端 ELO",
    en: "Frontend ELO",
    ja: "フロントエンドELO",
    ko: "프론트엔드 ELO",
  },
  "Frontend Win Rate": {
    "zh-CN": "前端胜率",
    "zh-TW": "前端勝率",
    en: "Frontend Win Rate",
    ja: "フロントエンド勝率",
    ko: "프론트엔드 승률",
  },
  "Fullstack App Quality": {
    "zh-CN": "全栈应用质量",
    "zh-TW": "全棧應用品質",
    en: "Fullstack App Quality",
    ja: "フルスタックアプリ品質",
    ko: "풀스택 앱 품질",
  },
  "全栈应用质量": {
    "zh-CN": "全栈应用质量",
    "zh-TW": "全棧應用品質",
    en: "Fullstack App Quality",
    ja: "フルスタックアプリ品質",
    ko: "풀스택 앱 품질",
  },
  "Backend Scores": {
    "zh-CN": "后端能力评分",
    "zh-TW": "後端能力評分",
    en: "Backend Scores",
    ja: "バックエンドスコア",
    ko: "백엔드 점수",
  },
  后端评分榜: {
    "zh-CN": "后端能力评分榜",
    "zh-TW": "後端能力評分榜",
    en: "Backend Scores",
    ja: "バックエンドスコア",
    ko: "백엔드 점수",
  },
  "Daily Usage": {
    "zh-CN": "日活使用",
    "zh-TW": "日活使用",
    en: "Daily Usage",
    ja: "デイリー利用",
    ko: "일일 사용량",
  },
  "Real-World Reach": {
    "zh-CN": "真实触达",
    "zh-TW": "真實觸達",
    en: "Real-World Reach",
    ja: "実利用リーチ",
    ko: "실사용 도달",
  },
  "Returning Users": {
    "zh-CN": "回访用户",
    "zh-TW": "回訪使用者",
    en: "Returning Users",
    ja: "リピート利用者",
    ko: "재방문 사용자",
  },
  "App Downloads": {
    "zh-CN": "应用下载",
    "zh-TW": "應用下載",
    en: "App Downloads",
    ja: "アプリダウンロード",
    ko: "앱 다운로드",
  },
  Code: {
    "zh-CN": "代码",
    "zh-TW": "程式",
    en: "Code",
    ja: "コード",
    ko: "코드",
  },
  Agent: {
    "zh-CN": "智能体",
    "zh-TW": "智能體",
    en: "Agent",
    ja: "エージェント",
    ko: "에이전트",
  },
  Vision: {
    "zh-CN": "视觉",
    "zh-TW": "視覺",
    en: "Vision",
    ja: "ビジョン",
    ko: "비전",
  },
  Document: {
    "zh-CN": "文档",
    "zh-TW": "文件",
    en: "Document",
    ja: "ドキュメント",
    ko: "문서",
  },
  Search: {
    "zh-CN": "搜索",
    "zh-TW": "搜尋",
    en: "Search",
    ja: "検索",
    ko: "검색",
  },
  WebDev: {
    "zh-CN": "Web 开发",
    "zh-TW": "Web 開發",
    en: "WebDev",
    ja: "Web開発",
    ko: "웹 개발",
  },
  Website: {
    "zh-CN": "网站",
    "zh-TW": "網站",
    en: "Website",
    ja: "Webサイト",
    ko: "웹사이트",
  },
  "Website Win Rate": {
    "zh-CN": "网站胜率",
    "zh-TW": "網站勝率",
    en: "Website Win Rate",
    ja: "Webサイト勝率",
    ko: "웹사이트 승률",
  },
  "UI Component": {
    "zh-CN": "UI 组件",
    "zh-TW": "UI 元件",
    en: "UI Component",
    ja: "UIコンポーネント",
    ko: "UI 컴포넌트",
  },
  "Data Visualization": {
    "zh-CN": "数据可视化",
    "zh-TW": "資料視覺化",
    en: "Data Visualization",
    ja: "データ可視化",
    ko: "데이터 시각화",
  },
  "Game Dev": {
    "zh-CN": "游戏开发",
    "zh-TW": "遊戲開發",
    en: "Game Dev",
    ja: "ゲーム開発",
    ko: "게임 개발",
  },
  "Agentic Game Dev": {
    "zh-CN": "Agentic 游戏开发",
    "zh-TW": "Agentic 遊戲開發",
    en: "Agentic Game Dev",
    ja: "Agenticゲーム開発",
    ko: "Agentic 게임 개발",
  },
  "Mobile App": {
    "zh-CN": "移动 App",
    "zh-TW": "行動 App",
    en: "Mobile App",
    ja: "モバイルApp",
    ko: "모바일 앱",
  },
  "Native App": {
    "zh-CN": "原生 App",
    "zh-TW": "原生 App",
    en: "Native App",
    ja: "ネイティブApp",
    ko: "네이티브 앱",
  },
  "3D Design": {
    "zh-CN": "3D 设计",
    "zh-TW": "3D 設計",
    en: "3D Design",
    ja: "3Dデザイン",
    ko: "3D 디자인",
  },
  SVG: {
    "zh-CN": "SVG",
    "zh-TW": "SVG",
    en: "SVG",
    ja: "SVG",
    ko: "SVG",
  },
  "ASCII Art": {
    "zh-CN": "ASCII Art",
    "zh-TW": "ASCII Art",
    en: "ASCII Art",
    ja: "ASCII Art",
    ko: "ASCII Art",
  },
  "Agentic Slides": {
    "zh-CN": "Agentic 演示文稿",
    "zh-TW": "Agentic 簡報",
    en: "Agentic Slides",
    ja: "Agenticスライド",
    ko: "Agentic 슬라이드",
  },
  "Agentic HTML Slides": {
    "zh-CN": "Agentic HTML 演示文稿",
    "zh-TW": "Agentic HTML 簡報",
    en: "Agentic HTML Slides",
    ja: "Agentic HTMLスライド",
    ko: "Agentic HTML 슬라이드",
  },
  Slides: {
    "zh-CN": "演示文稿",
    "zh-TW": "簡報",
    en: "Slides",
    ja: "スライド",
    ko: "슬라이드",
  },
  Image: {
    "zh-CN": "图像",
    "zh-TW": "圖像",
    en: "Image",
    ja: "画像",
    ko: "이미지",
  },
  "Image Editing": {
    "zh-CN": "图像编辑",
    "zh-TW": "圖像編輯",
    en: "Image Editing",
    ja: "画像編集",
    ko: "이미지 편집",
  },
  "Graphic Design": {
    "zh-CN": "平面设计",
    "zh-TW": "平面設計",
    en: "Graphic Design",
    ja: "グラフィックデザイン",
    ko: "그래픽 디자인",
  },
  Logo: {
    "zh-CN": "Logo",
    "zh-TW": "Logo",
    en: "Logo",
    ja: "Logo",
    ko: "Logo",
  },
  Video: {
    "zh-CN": "视频",
    "zh-TW": "影片",
    en: "Video",
    ja: "動画",
    ko: "비디오",
  },
  "Video Editing": {
    "zh-CN": "视频编辑",
    "zh-TW": "影片編輯",
    en: "Video Editing",
    ja: "動画編集",
    ko: "비디오 편집",
  },
  "Image to Video": {
    "zh-CN": "图像转视频",
    "zh-TW": "圖像轉影片",
    en: "Image to Video",
    ja: "画像から動画",
    ko: "이미지 비디오",
  },
  "Multi to Video": {
    "zh-CN": "多输入转视频",
    "zh-TW": "多輸入轉影片",
    en: "Multi to Video",
    ja: "マルチ入力動画",
    ko: "멀티 입력 비디오",
  },
  "Multimodal to Video": {
    "zh-CN": "多模态转视频",
    "zh-TW": "多模態轉影片",
    en: "Multimodal to Video",
    ja: "マルチモーダル動画",
    ko: "멀티모달 비디오",
  },
  TTS: {
    "zh-CN": "TTS",
    "zh-TW": "TTS",
    en: "TTS",
    ja: "TTS",
    ko: "TTS",
  },
  "AI Builder": {
    "zh-CN": "AI 构建器",
    "zh-TW": "AI 建構器",
    en: "AI Builder",
    ja: "AIビルダー",
    ko: "AI 빌더",
  },
  HTML: {
    "zh-CN": "HTML",
    "zh-TW": "HTML",
    en: "HTML",
    ja: "HTML",
    ko: "HTML",
  },
  React: {
    "zh-CN": "React",
    "zh-TW": "React",
    en: "React",
    ja: "React",
    ko: "React",
  },
  "Image to WebDev": {
    "zh-CN": "图像转 Web 开发",
    "zh-TW": "圖像轉 Web 開發",
    en: "Image to WebDev",
    ja: "画像からWeb開発",
    ko: "이미지 기반 웹 개발",
  },
  "Text to Image": {
    "zh-CN": "文本生成图像",
    "zh-TW": "文字生成圖像",
    en: "Text to Image",
    ja: "テキストから画像",
    ko: "텍스트 이미지 생성",
  },
  "Image Edit": {
    "zh-CN": "图像编辑",
    "zh-TW": "圖像編輯",
    en: "Image Edit",
    ja: "画像編集",
    ko: "이미지 편집",
  },
  "Text to Video": {
    "zh-CN": "文本生成视频",
    "zh-TW": "文字生成影片",
    en: "Text to Video",
    ja: "テキストから動画",
    ko: "텍스트 비디오 생성",
  },
  "Image to Video": {
    "zh-CN": "图像生成视频",
    "zh-TW": "圖像生成影片",
    en: "Image to Video",
    ja: "画像から動画",
    ko: "이미지 비디오 생성",
  },
  "Video Edit": {
    "zh-CN": "视频编辑",
    "zh-TW": "影片編輯",
    en: "Video Edit",
    ja: "動画編集",
    ko: "비디오 편집",
  },
  App: {
    "zh-CN": "App",
    "zh-TW": "App",
    en: "App",
    ja: "アプリ",
    ko: "앱",
  },
  PPT: {
    "zh-CN": "PPT",
    "zh-TW": "PPT",
    en: "PPT",
    ja: "PPT",
    ko: "PPT",
  },
  "Vibe Coding": {
    "zh-CN": "Vibe Coding",
    "zh-TW": "Vibe Coding",
    en: "Vibe Coding",
    ja: "Vibe Coding",
    ko: "Vibe Coding",
  },
  "Claw Agent": {
    "zh-CN": "Claw Agent",
    "zh-TW": "Claw Agent",
    en: "Claw Agent",
    ja: "Claw Agent",
    ko: "Claw Agent",
  },
  Skills: {
    "zh-CN": "技能",
    "zh-TW": "技能",
    en: "Skills",
    ja: "スキル",
    ko: "스킬",
  },
  Plugins: {
    "zh-CN": "插件",
    "zh-TW": "外掛",
    en: "Plugins",
    ja: "プラグイン",
    ko: "플러그인",
  },
  "Data Visualization": {
    "zh-CN": "数据可视化",
    "zh-TW": "資料視覺化",
    en: "Data Visualization",
    ja: "データ可視化",
    ko: "데이터 시각화",
  },
  Website: {
    "zh-CN": "网站",
    "zh-TW": "網站",
    en: "Website",
    ja: "Webサイト",
    ko: "웹사이트",
  },
  "UI Component": {
    "zh-CN": "UI 组件",
    "zh-TW": "UI 元件",
    en: "UI Component",
    ja: "UI コンポーネント",
    ko: "UI 컴포넌트",
  },
  DataViz: {
    "zh-CN": "数据可视化",
    "zh-TW": "資料視覺化",
    en: "DataViz",
    ja: "データ可視化",
    ko: "데이터 시각화",
  },
  SVG: {
    "zh-CN": "SVG",
    "zh-TW": "SVG",
    en: "SVG",
    ja: "SVG",
    ko: "SVG",
  },
  "Game Dev": {
    "zh-CN": "游戏开发",
    "zh-TW": "遊戲開發",
    en: "Game Dev",
    ja: "ゲーム開発",
    ko: "게임 개발",
  },
  "3D": {
    "zh-CN": "3D",
    "zh-TW": "3D",
    en: "3D",
    ja: "3D",
    ko: "3D",
  },
  "3D Design": {
    "zh-CN": "3D 设计",
    "zh-TW": "3D 設計",
    en: "3D Design",
    ja: "3Dデザイン",
    ko: "3D 디자인",
  },
  Slides: {
    "zh-CN": "演示文稿",
    "zh-TW": "簡報",
    en: "Slides",
    ja: "スライド",
    ko: "슬라이드",
  },
  Image: {
    "zh-CN": "图像",
    "zh-TW": "圖像",
    en: "Image",
    ja: "画像",
    ko: "이미지",
  },
  Video: {
    "zh-CN": "视频",
    "zh-TW": "影片",
    en: "Video",
    ja: "動画",
    ko: "비디오",
  },
};

const COMMON_SUBTYPE_LABEL_OVERRIDES = {
  热榜: {
    "zh-CN": "热榜",
    "zh-TW": "熱榜",
    en: "Hot List",
    ja: "人気ランキング",
    ko: "인기 랭킹",
  },
  新浪热榜: {
    "zh-CN": "新浪热榜",
    "zh-TW": "新浪熱榜",
    en: "Sina Hot List",
    ja: "Sina人気ランキング",
    ko: "Sina 인기 랭킹",
  },
  热搜: {
    "zh-CN": "热搜",
    "zh-TW": "熱搜",
    en: "Realtime",
    ja: "急上昇",
    ko: "실시간",
  },
  热搜榜: {
    "zh-CN": "热搜榜",
    "zh-TW": "熱搜榜",
    en: "Hot Search",
    ja: "急上昇検索",
    ko: "인기 검색어",
  },
  热门榜: {
    "zh-CN": "热门榜",
    "zh-TW": "熱門榜",
    en: "Popular Rankings",
    ja: "人気ランキング",
    ko: "인기 랭킹",
  },
  热议榜: {
    "zh-CN": "热议榜",
    "zh-TW": "熱議榜",
    en: "Hot Discussions",
    ja: "話題の議論",
    ko: "화제 토론",
  },
  热点榜: {
    "zh-CN": "热点榜",
    "zh-TW": "熱點榜",
    en: "Hot Topics",
    ja: "注目トピック",
    ko: "인기 토픽",
  },
  今日热门: {
    "zh-CN": "今日热门",
    "zh-TW": "今日熱門",
    en: "Today Trending",
    ja: "今日の人気",
    ko: "오늘의 인기",
  },
  中文网: {
    "zh-CN": "中文网",
    "zh-TW": "中文網",
    en: "Chinese Site",
    ja: "中国語版",
    ko: "중국어판",
  },
  讨论精选: {
    "zh-CN": "讨论精选",
    "zh-TW": "討論精選",
    en: "Curated Discussions",
    ja: "議論ピックアップ",
    ko: "추천 토론",
  },
  人气榜: {
    "zh-CN": "人气榜",
    "zh-TW": "人氣榜",
    en: "Popularity Rankings",
    ja: "人気ランキング",
    ko: "인기 랭킹",
  },
  最新资讯: {
    "zh-CN": "最新资讯",
    "zh-TW": "最新資訊",
    en: "Latest News",
    ja: "最新ニュース",
    ko: "최신 뉴스",
  },
  最新动态: {
    "zh-CN": "最新动态",
    "zh-TW": "最新動態",
    en: "Latest Updates",
    ja: "最新アップデート",
    ko: "최신 업데이트",
  },
  更新公告: {
    "zh-CN": "更新公告",
    "zh-TW": "更新公告",
    en: "Update Notices",
    ja: "更新告知",
    ko: "업데이트 공지",
  },
  最新公告: {
    "zh-CN": "最新公告",
    "zh-TW": "最新公告",
    en: "Latest Notices",
    ja: "最新告知",
    ko: "최신 공지",
  },
  全部文章: {
    "zh-CN": "全部文章",
    "zh-TW": "全部文章",
    en: "All Articles",
    ja: "すべての記事",
    ko: "전체 글",
  },
  地震速报: {
    "zh-CN": "地震速报",
    "zh-TW": "地震速報",
    en: "Earthquake Alerts",
    ja: "地震速報",
    ko: "지진 속보",
  },
  热门推荐: {
    "zh-CN": "热门推荐",
    "zh-TW": "熱門推薦",
    en: "Popular Picks",
    ja: "人気おすすめ",
    ko: "인기 추천",
  },
  全国气象预警: {
    "zh-CN": "全国气象预警",
    "zh-TW": "全國氣象預警",
    en: "National Weather Alerts",
    ja: "全国気象警報",
    ko: "전국 기상 특보",
  },
  飙升榜: {
    "zh-CN": "飙升榜",
    "zh-TW": "飆升榜",
    en: "Rising",
    ja: "急上昇",
    ko: "급상승",
  },
  最新精华: {
    "zh-CN": "最新精华",
    "zh-TW": "最新精華",
    en: "Latest Featured",
    ja: "最新ピックアップ",
    ko: "최신 추천",
  },
  步行街热帖: {
    "zh-CN": "步行街热帖",
    "zh-TW": "步行街熱帖",
    en: "Hupu Hot Posts",
    ja: "Hupu人気投稿",
    ko: "Hupu 인기 게시글",
  },
  热门话题: {
    "zh-CN": "热门话题",
    "zh-TW": "熱門話題",
    en: "Hot Topics",
    ja: "人気トピック",
    ko: "인기 토픽",
  },
  论坛热帖: {
    "zh-CN": "论坛热帖",
    "zh-TW": "論壇熱帖",
    en: "Forum Hot Posts",
    ja: "フォーラム人気投稿",
    ko: "포럼 인기 게시글",
  },
  官方首页: {
    "zh-CN": "官方首页",
    "zh-TW": "官方首頁",
    en: "Official Home",
    ja: "公式ホーム",
    ko: "공식 홈",
  },
  主题榜: {
    "zh-CN": "主题榜",
    "zh-TW": "主題榜",
    en: "Topic Rankings",
    ja: "トピックランキング",
    ko: "주제 랭킹",
  },
  推荐榜: {
    "zh-CN": "推荐榜",
    "zh-TW": "推薦榜",
    en: "Recommended",
    ja: "おすすめ",
    ko: "추천",
  },
  热门动态: {
    "zh-CN": "热门动态",
    "zh-TW": "熱門動態",
    en: "Popular Updates",
    ja: "人気アップデート",
    ko: "인기 업데이트",
  },
  热门文章: {
    "zh-CN": "热门文章",
    "zh-TW": "熱門文章",
    en: "Popular Articles",
    ja: "人気記事",
    ko: "인기 글",
  },
  热门仓库: {
    "zh-CN": "热门仓库",
    "zh-TW": "熱門倉庫",
    en: "Trending Repositories",
    ja: "人気リポジトリ",
    ko: "인기 저장소",
  },
  "24小时": {
    "zh-CN": "24小时",
    "zh-TW": "24小時",
    en: "24 Hours",
    ja: "24時間",
    ko: "24시간",
  },
  快讯: {
    "zh-CN": "快讯",
    "zh-TW": "快訊",
    en: "Briefs",
    ja: "速報",
    ko: "속보",
  },
  文章榜: {
    "zh-CN": "文章榜",
    "zh-TW": "文章榜",
    en: "Articles",
    ja: "記事",
    ko: "글",
  },
  "官方 Feed": {
    "zh-CN": "官方 Feed",
    "zh-TW": "官方 Feed",
    en: "Official Feed",
    ja: "公式フィード",
    ko: "공식 피드",
  },
  "排行榜 · 综合": {
    "zh-CN": "排行榜 · 综合",
    "zh-TW": "排行榜 · 綜合",
    en: "Rankings · General",
    ja: "ランキング · 総合",
    ko: "랭킹 · 종합",
  },
  "热榜 · 全站": {
    "zh-CN": "热榜 · 全站",
    "zh-TW": "熱榜 · 全站",
    en: "Hot List · Sitewide",
    ja: "人気ランキング · 全体",
    ko: "인기 랭킹 · 전체",
  },
  最新热门: {
    "zh-CN": "最新热门",
    "zh-TW": "最新熱門",
    en: "Latest Hot",
    ja: "最新人気",
    ko: "최신 인기",
  },
  默认: {
    "zh-CN": "默认",
    "zh-TW": "預設",
    en: "Default",
    ja: "デフォルト",
    ko: "기본",
  },
  排行: {
    "zh-CN": "排行",
    "zh-TW": "排行",
    en: "Rankings",
    ja: "ランキング",
    ko: "랭킹",
  },
  日榜: {
    "zh-CN": "日榜",
    "zh-TW": "日榜",
    en: "Daily",
    ja: "日次",
    ko: "일간",
  },
  周榜: {
    "zh-CN": "周榜",
    "zh-TW": "週榜",
    en: "Weekly",
    ja: "週間",
    ko: "주간",
  },
  月榜: {
    "zh-CN": "月榜",
    "zh-TW": "月榜",
    en: "Monthly",
    ja: "月間",
    ko: "월간",
  },
  资讯热榜: {
    "zh-CN": "资讯热榜",
    "zh-TW": "資訊熱榜",
    en: "News Hot List",
    ja: "ニュース人気ランキング",
    ko: "뉴스 인기 랭킹",
  },
  滚动新闻: {
    "zh-CN": "滚动新闻",
    "zh-TW": "滾動新聞",
    en: "News Feed",
    ja: "ニュースフィード",
    ko: "뉴스 피드",
  },
  视频排行: {
    "zh-CN": "视频排行",
    "zh-TW": "影片排行",
    en: "Video Rankings",
    ja: "動画ランキング",
    ko: "동영상 랭킹",
  },
  图片排行: {
    "zh-CN": "图片排行",
    "zh-TW": "圖片排行",
    en: "Image Rankings",
    ja: "画像ランキング",
    ko: "이미지 랭킹",
  },
  国内新闻: {
    "zh-CN": "国内新闻",
    "zh-TW": "國內新聞",
    en: "Domestic News",
    ja: "国内ニュース",
    ko: "국내 뉴스",
  },
  国际新闻: {
    "zh-CN": "国际新闻",
    "zh-TW": "國際新聞",
    en: "World News",
    ja: "国際ニュース",
    ko: "국제 뉴스",
  },
  社会新闻: {
    "zh-CN": "社会新闻",
    "zh-TW": "社會新聞",
    en: "Society News",
    ja: "社会ニュース",
    ko: "사회 뉴스",
  },
  体育新闻: {
    "zh-CN": "体育新闻",
    "zh-TW": "體育新聞",
    en: "Sports News",
    ja: "スポーツニュース",
    ko: "스포츠 뉴스",
  },
  财经新闻: {
    "zh-CN": "财经新闻",
    "zh-TW": "財經新聞",
    en: "Finance News",
    ja: "経済ニュース",
    ko: "경제 뉴스",
  },
  娱乐新闻: {
    "zh-CN": "娱乐新闻",
    "zh-TW": "娛樂新聞",
    en: "Entertainment News",
    ja: "エンタメニュース",
    ko: "연예 뉴스",
  },
  科技新闻: {
    "zh-CN": "科技新闻",
    "zh-TW": "科技新聞",
    en: "Tech News",
    ja: "テックニュース",
    ko: "기술 뉴스",
  },
  军事新闻: {
    "zh-CN": "军事新闻",
    "zh-TW": "軍事新聞",
    en: "Military News",
    ja: "軍事ニュース",
    ko: "군사 뉴스",
  },
  周热门: {
    "zh-CN": "周热门",
    "zh-TW": "週熱門",
    en: "Weekly Hot",
    ja: "週間人気",
    ko: "주간 인기",
  },
  月热门: {
    "zh-CN": "月热门",
    "zh-TW": "月熱門",
    en: "Monthly Hot",
    ja: "月間人気",
    ko: "월간 인기",
  },
  视频热榜: {
    "zh-CN": "视频热榜",
    "zh-TW": "影片熱榜",
    en: "Video Hot List",
    ja: "動画人気ランキング",
    ko: "동영상 인기 랭킹",
  },
  娱乐热榜: {
    "zh-CN": "娱乐热榜",
    "zh-TW": "娛樂熱榜",
    en: "Entertainment Hot List",
    ja: "エンタメ人気ランキング",
    ko: "연예 인기 랭킹",
  },
  AI热榜: {
    "zh-CN": "AI热榜",
    "zh-TW": "AI熱榜",
    en: "AI Hot List",
    ja: "AI人気ランキング",
    ko: "AI 인기 랭킹",
  },
  汽车热榜: {
    "zh-CN": "汽车热榜",
    "zh-TW": "汽車熱榜",
    en: "Auto Hot List",
    ja: "自動車人気ランキング",
    ko: "자동차 인기 랭킹",
  },
  育儿热榜: {
    "zh-CN": "育儿热榜",
    "zh-TW": "育兒熱榜",
    en: "Parenting Hot List",
    ja: "育児人気ランキング",
    ko: "육아 인기 랭킹",
  },
  时尚热榜: {
    "zh-CN": "时尚热榜",
    "zh-TW": "時尚熱榜",
    en: "Fashion Hot List",
    ja: "ファッション人気ランキング",
    ko: "패션 인기 랭킹",
  },
  旅游热榜: {
    "zh-CN": "旅游热榜",
    "zh-TW": "旅遊熱榜",
    en: "Travel Hot List",
    ja: "旅行人気ランキング",
    ko: "여행 인기 랭킹",
  },
  ESG热榜: {
    "zh-CN": "ESG热榜",
    "zh-TW": "ESG熱榜",
    en: "ESG Hot List",
    ja: "ESG人気ランキング",
    ko: "ESG 인기 랭킹",
  },
  新书榜: {
    "zh-CN": "新书榜",
    "zh-TW": "新書榜",
    en: "New Books",
    ja: "新刊",
    ko: "신간",
  },
  小说榜: {
    "zh-CN": "小说榜",
    "zh-TW": "小說榜",
    en: "Novels",
    ja: "小説",
    ko: "소설",
  },
  视频榜: {
    "zh-CN": "视频榜",
    "zh-TW": "影片榜",
    en: "Videos",
    ja: "動画",
    ko: "동영상",
  },
  收藏榜: {
    "zh-CN": "收藏榜",
    "zh-TW": "收藏榜",
    en: "Most Saved",
    ja: "保存ランキング",
    ko: "저장 랭킹",
  },
  主干道: {
    "zh-CN": "主干道",
    "zh-TW": "主幹道",
    en: "Main Street",
    ja: "メインストリート",
    ko: "메인 스트리트",
  },
  恋爱区: {
    "zh-CN": "恋爱区",
    "zh-TW": "戀愛區",
    en: "Relationships",
    ja: "恋愛",
    ko: "연애",
  },
  校园区: {
    "zh-CN": "校园区",
    "zh-TW": "校園區",
    en: "Campus",
    ja: "キャンパス",
    ko: "캠퍼스",
  },
  历史区: {
    "zh-CN": "历史区",
    "zh-TW": "歷史區",
    en: "History",
    ja: "歴史",
    ko: "역사",
  },
  摄影区: {
    "zh-CN": "摄影区",
    "zh-TW": "攝影區",
    en: "Photography",
    ja: "写真",
    ko: "사진",
  },
  最热主题: {
    "zh-CN": "最热主题",
    "zh-TW": "最熱主題",
    en: "Hottest Topics",
    ja: "最も人気のトピック",
    ko: "최고 인기 주제",
  },
  最新主题: {
    "zh-CN": "最新主题",
    "zh-TW": "最新主題",
    en: "Latest Topics",
    ja: "最新トピック",
    ko: "최신 주제",
  },
  公告: {
    "zh-CN": "公告",
    "zh-TW": "公告",
    en: "Notices",
    ja: "お知らせ",
    ko: "공지",
  },
  活动: {
    "zh-CN": "活动",
    "zh-TW": "活動",
    en: "Events",
    ja: "イベント",
    ko: "이벤트",
  },
  资讯: {
    "zh-CN": "资讯",
    "zh-TW": "資訊",
    en: "News",
    ja: "ニュース",
    ko: "뉴스",
  },
  应用推荐: {
    "zh-CN": "应用推荐",
    "zh-TW": "應用推薦",
    en: "App Picks",
    ja: "アプリおすすめ",
    ko: "앱 추천",
  },
  生活方式: {
    "zh-CN": "生活方式",
    "zh-TW": "生活方式",
    en: "Lifestyle",
    ja: "ライフスタイル",
    ko: "라이프스타일",
  },
  效率技巧: {
    "zh-CN": "效率技巧",
    "zh-TW": "效率技巧",
    en: "Productivity",
    ja: "生産性",
    ko: "생산성",
  },
  少数派播客: {
    "zh-CN": "少数派播客",
    "zh-TW": "少數派播客",
    en: "sspai Podcasts",
    ja: "sspaiポッドキャスト",
    ko: "sspai 팟캐스트",
  },
  鬼畜: {
    "zh-CN": "鬼畜",
    "zh-TW": "鬼畜",
    en: "Kichiku",
    ja: "鬼畜",
    ko: "키치쿠",
  },
  舞蹈: {
    "zh-CN": "舞蹈",
    "zh-TW": "舞蹈",
    en: "Dance",
    ja: "ダンス",
    ko: "댄스",
  },
  时尚: {
    "zh-CN": "时尚",
    "zh-TW": "時尚",
    en: "Fashion",
    ja: "ファッション",
    ko: "패션",
  },
  生活: {
    "zh-CN": "生活",
    "zh-TW": "生活",
    en: "Life",
    ja: "ライフ",
    ko: "생활",
  },
  国创相关: {
    "zh-CN": "国创相关",
    "zh-TW": "國創相關",
    en: "Chinese Animation",
    ja: "中国アニメ",
    ko: "중국 애니메이션",
  },
  影视: {
    "zh-CN": "影视",
    "zh-TW": "影視",
    en: "Film & TV",
    ja: "映画・テレビ",
    ko: "영상",
  },
  体育: {
    "zh-CN": "体育",
    "zh-TW": "體育",
    en: "Sports",
    ja: "スポーツ",
    ko: "스포츠",
  },
  科技: {
    "zh-CN": "科技",
    "zh-TW": "科技",
    en: "Tech",
    ja: "テック",
    ko: "기술",
  },
  舞蹈·偶像: {
    "zh-CN": "舞蹈·偶像",
    "zh-TW": "舞蹈·偶像",
    en: "Dance & Idols",
    ja: "ダンス・アイドル",
    ko: "댄스·아이돌",
  },
  鱼塘: {
    "zh-CN": "鱼塘",
    "zh-TW": "魚塘",
    en: "Community",
    ja: "コミュニティ",
    ko: "커뮤니티",
  },
  番剧: {
    "zh-CN": "番剧",
    "zh-TW": "番劇",
    en: "Anime Series",
    ja: "アニメ番組",
    ko: "애니 시리즈",
  },
  后端: {
    "zh-CN": "后端",
    "zh-TW": "後端",
    en: "Backend",
    ja: "バックエンド",
    ko: "백엔드",
  },
  前端: {
    "zh-CN": "前端",
    "zh-TW": "前端",
    en: "Frontend",
    ja: "フロントエンド",
    ko: "프론트엔드",
  },
  人工智能: {
    "zh-CN": "人工智能",
    "zh-TW": "人工智慧",
    en: "AI",
    ja: "AI",
    ko: "AI",
  },
  开发工具: {
    "zh-CN": "开发工具",
    "zh-TW": "開發工具",
    en: "Dev Tools",
    ja: "開発ツール",
    ko: "개발 도구",
  },
  代码人生: {
    "zh-CN": "代码人生",
    "zh-TW": "代碼人生",
    en: "Developer Life",
    ja: "開発者ライフ",
    ko: "개발자 생활",
  },
  阅读: {
    "zh-CN": "阅读",
    "zh-TW": "閱讀",
    en: "Reading",
    ja: "読書",
    ko: "읽기",
  },
  全站: {
    "zh-CN": "全站",
    "zh-TW": "全站",
    en: "Sitewide",
    ja: "全体",
    ko: "전체",
  },
  总排行: {
    "zh-CN": "总排行",
    "zh-TW": "總排行",
    en: "Overall",
    ja: "総合ランキング",
    ko: "종합 랭킹",
  },
  总榜: {
    "zh-CN": "总榜",
    "zh-TW": "總榜",
    en: "Overall",
    ja: "総合",
    ko: "종합",
  },
  开源榜: {
    "zh-CN": "开源榜",
    "zh-TW": "開源榜",
    en: "Open Source",
    ja: "オープンソース",
    ko: "오픈소스",
  },
  小说: {
    "zh-CN": "小说",
    "zh-TW": "小說",
    en: "Novel",
    ja: "小説",
    ko: "소설",
  },
  电影: {
    "zh-CN": "电影",
    "zh-TW": "電影",
    en: "Movie",
    ja: "映画",
    ko: "영화",
  },
  电视剧: {
    "zh-CN": "电视剧",
    "zh-TW": "電視劇",
    en: "TV",
    ja: "ドラマ",
    ko: "드라마",
  },
  汽车: {
    "zh-CN": "汽车",
    "zh-TW": "汽車",
    en: "Cars",
    ja: "自動車",
    ko: "자동차",
  },
  游戏: {
    "zh-CN": "游戏",
    "zh-TW": "遊戲",
    en: "Games",
    ja: "ゲーム",
    ko: "게임",
  },
  最新回复: {
    "zh-CN": "最新回复",
    "zh-TW": "最新回覆",
    en: "Latest Replies",
    ja: "最新返信",
    ko: "최신 댓글",
  },
  最新发表: {
    "zh-CN": "最新发表",
    "zh-TW": "最新發表",
    en: "Latest Posts",
    ja: "最新投稿",
    ko: "최신 게시글",
  },
  首页: {
    "zh-CN": "首页",
    "zh-TW": "首頁",
    en: "Home",
    ja: "ホーム",
    ko: "홈",
  },
  精品: {
    "zh-CN": "精品",
    "zh-TW": "精選",
    en: "Featured",
    ja: "注目",
    ko: "추천",
  },
  热映: {
    "zh-CN": "热映",
    "zh-TW": "熱映",
    en: "Now Showing",
    ja: "上映中",
    ko: "상영 중",
  },
  新片榜: {
    "zh-CN": "新片榜",
    "zh-TW": "新片榜",
    en: "New Releases",
    ja: "新作",
    ko: "신작",
  },
  热门: {
    "zh-CN": "热门",
    "zh-TW": "熱門",
    en: "Popular",
    ja: "人気",
    ko: "인기",
  },
  所有: {
    "zh-CN": "所有",
    "zh-TW": "所有",
    en: "All",
    ja: "すべて",
    ko: "전체",
  },
  娱乐: {
    "zh-CN": "娱乐",
    "zh-TW": "娛樂",
    en: "Entertainment",
    ja: "エンタメ",
    ko: "엔터테인먼트",
  },
  热门电影: {
    "zh-CN": "热门电影",
    "zh-TW": "熱門電影",
    en: "Popular Movies",
    ja: "人気映画",
    ko: "인기 영화",
  },
  最新电影: {
    "zh-CN": "最新电影",
    "zh-TW": "最新電影",
    en: "Latest Movies",
    ja: "最新映画",
    ko: "최신 영화",
  },
  电视剧综合: {
    "zh-CN": "电视剧综合",
    "zh-TW": "電視劇綜合",
    en: "TV · General",
    ja: "ドラマ総合",
    ko: "드라마 종합",
  },
  最新: {
    "zh-CN": "最新",
    "zh-TW": "最新",
    en: "Latest",
    ja: "最新",
    ko: "최신",
  },
  综合: {
    "zh-CN": "综合",
    "zh-TW": "綜合",
    en: "General",
    ja: "総合",
    ko: "종합",
  },
  国产剧: {
    "zh-CN": "国产剧",
    "zh-TW": "國產劇",
    en: "Chinese Dramas",
    ja: "中国ドラマ",
    ko: "중국 드라마",
  },
  综艺: {
    "zh-CN": "综艺",
    "zh-TW": "綜藝",
    en: "Variety",
    ja: "バラエティ",
    ko: "예능",
  },
  欧美剧: {
    "zh-CN": "欧美剧",
    "zh-TW": "歐美劇",
    en: "Western Dramas",
    ja: "欧米ドラマ",
    ko: "서구권 드라마",
  },
  日剧: {
    "zh-CN": "日剧",
    "zh-TW": "日劇",
    en: "Japanese Dramas",
    ja: "日本ドラマ",
    ko: "일본 드라마",
  },
  韩剧: {
    "zh-CN": "韩剧",
    "zh-TW": "韓劇",
    en: "Korean Dramas",
    ja: "韓国ドラマ",
    ko: "한국 드라마",
  },
  动画: {
    "zh-CN": "动画",
    "zh-TW": "動畫",
    en: "Animation",
    ja: "アニメ",
    ko: "애니메이션",
  },
  纪录片: {
    "zh-CN": "纪录片",
    "zh-TW": "紀錄片",
    en: "Documentary",
    ja: "ドキュメンタリー",
    ko: "다큐멘터리",
  },
  模型榜: {
    "zh-CN": "模型榜",
    "zh-TW": "模型榜",
    en: "Models",
    ja: "モデル",
    ko: "모델",
  },
  厂商榜: {
    "zh-CN": "厂商榜",
    "zh-TW": "廠商榜",
    en: "Providers",
    ja: "プロバイダ",
    ko: "프로바이더",
  },
  网站: {
    "zh-CN": "网站",
    "zh-TW": "網站",
    en: "Web",
    ja: "Webサイト",
    ko: "웹사이트",
  },
  云服务: {
    "zh-CN": "云服务",
    "zh-TW": "雲端服務",
    en: "Cloud",
    ja: "クラウドサービス",
    ko: "클라우드 서비스",
  },
  中国: {
    "zh-CN": "中国",
    "zh-TW": "中國",
    en: "China",
    ja: "中国",
    ko: "중국",
  },
  聊天: {
    "zh-CN": "聊天",
    "zh-TW": "聊天",
    en: "Chat",
    ja: "チャット",
    ko: "채팅",
  },
  搜索: {
    "zh-CN": "搜索",
    "zh-TW": "搜尋",
    en: "Search",
    ja: "検索",
    ko: "검색",
  },
  角色: {
    "zh-CN": "角色",
    "zh-TW": "角色",
    en: "Characters",
    ja: "キャラクター",
    ko: "캐릭터",
  },
  图片生成: {
    "zh-CN": "图片生成",
    "zh-TW": "圖片生成",
    en: "Image Gen",
    ja: "画像生成",
    ko: "이미지 생성",
  },
  图片编辑: {
    "zh-CN": "图片编辑",
    "zh-TW": "圖片編輯",
    en: "Image Edit",
    ja: "画像編集",
    ko: "이미지 편집",
  },
  视频生成: {
    "zh-CN": "视频生成",
    "zh-TW": "影片生成",
    en: "Video Gen",
    ja: "動画生成",
    ko: "비디오 생성",
  },
  视频编辑: {
    "zh-CN": "视频编辑",
    "zh-TW": "影片編輯",
    en: "Video Edit",
    ja: "動画編集",
    ko: "비디오 편집",
  },
  音乐: {
    "zh-CN": "音乐",
    "zh-TW": "音樂",
    en: "Music",
    ja: "音楽",
    ko: "음악",
  },
  会议: {
    "zh-CN": "会议",
    "zh-TW": "會議",
    en: "Meeting",
    ja: "会議",
    ko: "미팅",
  },
  全球增长: {
    "zh-CN": "全球增长",
    "zh-TW": "全球增長",
    en: "Global Growth",
    ja: "グローバル成長",
    ko: "글로벌 성장",
  },
  中国增长: {
    "zh-CN": "中国增长",
    "zh-TW": "中國增長",
    en: "China Growth",
    ja: "中国成長",
    ko: "중국 성장",
  },
  "Claw 增长": {
    "zh-CN": "Claw 增长",
    "zh-TW": "Claw 增長",
    en: "Claw Growth",
    ja: "Claw成長",
    ko: "Claw 성장",
  },
  全球放缓: {
    "zh-CN": "全球放缓",
    "zh-TW": "全球放緩",
    en: "Global Slowdown",
    ja: "グローバル減速",
    ko: "글로벌 둔화",
  },
  编程: {
    "zh-CN": "编程",
    "zh-TW": "程式",
    en: "Coding",
    ja: "コーディング",
    ko: "코딩",
  },
  写作: {
    "zh-CN": "写作",
    "zh-TW": "寫作",
    en: "Writing",
    ja: "ライティング",
    ko: "글쓰기",
  },
  数学: {
    "zh-CN": "数学",
    "zh-TW": "數學",
    en: "Math",
    ja: "数学",
    ko: "수학",
  },
  研究: {
    "zh-CN": "研究",
    "zh-TW": "研究",
    en: "Research",
    ja: "研究",
    ko: "연구",
  },
  长上下文: {
    "zh-CN": "长上下文",
    "zh-TW": "長上下文",
    en: "Long Context",
    ja: "長文脈",
    ko: "롱컨텍스트",
  },
  工具调用: {
    "zh-CN": "工具调用",
    "zh-TW": "工具調用",
    en: "Tool Calling",
    ja: "ツール利用",
    ko: "툴콜링",
  },
  推理: {
    "zh-CN": "推理",
    "zh-TW": "推理",
    en: "Reasoning",
    ja: "推論",
    ko: "추론",
  },
};

Object.assign(SUBTYPE_LABEL_OVERRIDES, COMMON_SUBTYPE_LABEL_OVERRIDES);

const containsNonLatin = (value = "") =>
  /[\u3040-\u30ff\u3400-\u9fff\uac00-\ud7af]/.test(value);

const normalizeLookupLabel = (value = "") =>
  String(value || "")
    .replace(/\s+/g, " ")
    .trim();

const titleCaseToken = (token = "") =>
  token
    .split(" ")
    .filter(Boolean)
    .map((part) =>
      /^[A-Z0-9]+$/.test(part)
        ? part
        : part.charAt(0).toUpperCase() + part.slice(1)
    )
    .join(" ");

export const prettifySlug = (value = "") =>
  titleCaseToken(
    String(value)
      .replace(/[-_]+/g, " ")
      .replace(/\s+/g, " ")
      .trim()
  );

export const getSourceLabel = (
  sourceName,
  locale = "zh-CN",
  fallbackLabel = "",
) => {
  const normalizedLocale = normalizeLocale(locale);
  const overrides = SOURCE_LABEL_OVERRIDES[sourceName] || null;
  if (overrides?.[normalizedLocale]) return overrides[normalizedLocale];
  if ((normalizedLocale === "zh-CN" || normalizedLocale === "zh-TW") && fallbackLabel) {
    return fallbackLabel;
  }
  if (overrides?.en) return overrides.en;
  if (fallbackLabel && !containsNonLatin(fallbackLabel)) return fallbackLabel;
  return prettifySlug(sourceName || fallbackLabel || "rankings");
};

const stripDisplaySuffix = (label = "", locale = "zh-CN") => {
  const normalizedLocale = normalizeLocale(locale);
  const suffixes = SOURCE_DISPLAY_SUFFIXES[normalizedLocale] || [];
  const normalizedLabel = normalizeLookupLabel(label);
  const suffix = suffixes.find(
    (item) =>
      normalizedLabel.endsWith(item) &&
      normalizedLabel.length > item.length + 1
  );
  if (!suffix) return normalizedLabel;
  return normalizeLookupLabel(normalizedLabel.slice(0, -suffix.length));
};

export const getSourceDisplayLabel = (
  sourceName,
  locale = "zh-CN",
  fallbackLabel = "",
) => {
  const normalizedLocale = normalizeLocale(locale);
  const fallbackDisplayLabel = stripDisplaySuffix(fallbackLabel, normalizedLocale);
  const overrides = SOURCE_DISPLAY_LABEL_OVERRIDES[sourceName] || null;
  if (overrides?.[normalizedLocale]) return overrides[normalizedLocale];
  if (normalizedLocale === "zh-CN" && fallbackDisplayLabel) {
    return fallbackDisplayLabel;
  }
  if (overrides?.en) return overrides.en;
  return stripDisplaySuffix(
    getSourceLabel(sourceName, normalizedLocale, fallbackLabel),
    normalizedLocale
  );
};

export const getSubtypeLabel = (item, locale = "zh-CN") => {
  const normalizedLocale = normalizeLocale(locale);
  const rawLabel = normalizeLookupLabel(item?.label || "");
  const fallbackKey = normalizeLookupLabel(item?.value || rawLabel);
  const override =
    SUBTYPE_LABEL_OVERRIDES[fallbackKey] || SUBTYPE_LABEL_OVERRIDES[rawLabel];
  if (override?.[normalizedLocale]) {
    return override[normalizedLocale];
  }
  if (!fallbackKey) return "";
  if (normalizedLocale === "zh-CN" || normalizedLocale === "zh-TW") {
    return rawLabel || prettifySlug(fallbackKey);
  }
  if (rawLabel && !containsNonLatin(rawLabel)) return rawLabel;
  return prettifySlug(fallbackKey);
};

export const getSourceSubtitleLabel = (label = "", locale = "zh-CN") => {
  const normalizedLocale = normalizeLocale(locale);
  const rawLabel = normalizeLookupLabel(label);
  const override = SUBTYPE_LABEL_OVERRIDES[rawLabel];
  if (override?.[normalizedLocale]) {
    return override[normalizedLocale];
  }
  if (!rawLabel) return "";
  const subtypeLabel = getSubtypeLabel(
    { label: rawLabel, value: rawLabel },
    normalizedLocale
  );
  if (subtypeLabel && subtypeLabel !== rawLabel) {
    return subtypeLabel;
  }
  if (normalizedLocale === "zh-CN" || normalizedLocale === "zh-TW") {
    return rawLabel;
  }
  if (!containsNonLatin(rawLabel)) {
    return rawLabel;
  }
  return prettifySlug(rawLabel);
};

export const isGenericSourceSubtitleLabel = (label = "", locale = "zh-CN") => {
  const normalizedLocale = normalizeLocale(locale);
  const normalizedLabel = normalizeLookupLabel(label);
  if (!normalizedLabel) return false;
  return (GENERIC_SOURCE_SUBTITLE_LABELS[normalizedLocale] || []).includes(
    normalizedLabel
  );
};

export const getSubtypeGroupLabel = (group, locale = "zh-CN") => {
  const normalizedLocale = normalizeLocale(locale);
  const rawLabel = normalizeLookupLabel(group?.label || "");
  const groupKey = normalizeLookupLabel(
    group?.key || rawLabel || group?.items?.[0]?.value || ""
  );
  const override = GROUP_LABEL_OVERRIDES[groupKey];
  if (override?.[normalizedLocale]) return override[normalizedLocale];
  const rawOverride = GROUP_LABEL_OVERRIDES[rawLabel];
  if (rawOverride?.[normalizedLocale]) return rawOverride[normalizedLocale];
  if (normalizedLocale === "zh-CN" || normalizedLocale === "zh-TW") {
    return rawLabel || getSubtypeLabel(group?.items?.[0], locale);
  }
  if (rawLabel && !containsNonLatin(rawLabel)) return rawLabel;
  return prettifySlug(groupKey);
};

export const localizeSubtypeGroups = (groups = [], locale = "zh-CN") =>
  groups.map((group) => ({
    ...group,
    label: getSubtypeGroupLabel(group, locale),
    items: (group.items || []).map((item) => ({
      ...item,
      label: getSubtypeLabel(item, locale),
    })),
  }));
